'use client'

import { AUDIT_FRAMEWORK } from '@/lib/seo-audit/framework'

// ── CSV export ────────────────────────────────────────────────────────────────
function downloadCSV(filename: string, rows: string[][]) {
  const csv = rows.map(r => r.map(c => `"${String(c ?? '').replace(/"/g, '""')}"`).join(',')).join('\n')
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename; a.click()
  URL.revokeObjectURL(url)
}

// ── PDF export (via print dialog) ────────────────────────────────────────────
function downloadPDF(filename: string, htmlContent: string) {
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(`<!DOCTYPE html><html><head>
    <title>${filename}</title>
    <style>
      body { font-family: Arial, sans-serif; font-size: 12px; color: #111; padding: 24px; max-width: 800px; margin: 0 auto; }
      h1 { font-size: 20px; color: #1e3a8a; border-bottom: 2px solid #2563eb; padding-bottom: 8px; margin-bottom: 16px; }
      h2 { font-size: 15px; color: #1e3a8a; margin: 16px 0 6px; }
      table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 11px; }
      th { background: #1e3a8a; color: white; padding: 6px 8px; text-align: left; }
      td { padding: 5px 8px; border-bottom: 1px solid #e5e7eb; }
      tr:nth-child(even) td { background: #f8fafc; }
      .badge { display: inline-block; padding: 2px 8px; border-radius: 99px; font-size: 10px; font-weight: bold; }
      .high { background: #fee2e2; color: #dc2626; }
      .medium { background: #fef3c7; color: #d97706; }
      .low { background: #f0fdf4; color: #16a34a; }
      .likely { background: #f0fdf4; color: #16a34a; }
      .possible { background: #fef3c7; color: #d97706; }
      .unlikely { background: #fee2e2; color: #dc2626; }
      p { margin: 4px 0 8px; line-height: 1.5; }
      .meta { color: #6b7280; font-size: 10px; margin-bottom: 16px; }
      @media print { body { padding: 0; } }
    </style>
  </head><body>${htmlContent}<script>window.onload=()=>{window.print();}</script></body></html>`)
  win.document.close()
}

// ── DOCX export (using docx npm package loaded via CDN) ───────────────────────
async function downloadDOCX(filename: string, buildFn: () => Promise<Uint8Array>) {
  const bytes = await buildFn()
  const blob = new Blob([bytes as any], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename + '.docx'; a.click()
  URL.revokeObjectURL(url)
}

// ─────────────────────────────────────────────────────────────────────────────
// CITE TRACKER EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type TrackerResult = {
  query: string; citation_likelihood: number; citation_verdict: string
  simulated_ai_response: string; reasons_for_citation: string[]
  reasons_against_citation: string[]; what_would_increase_citation: string
}

export function exportTrackerCSV(data: { overall_citation_score?: number; verdict?: string; results?: TrackerResult[] }) {
  const rows = [
    ['Query', 'Citation Score', 'Verdict', 'Simulated AI Response', 'Reasons For', 'Reasons Against', 'What Would Help'],
    ...(data.results ?? []).map(r => [
      r.query, String(r.citation_likelihood), r.citation_verdict,
      r.simulated_ai_response,
      (r.reasons_for_citation ?? []).join('; '),
      (r.reasons_against_citation ?? []).join('; '),
      r.what_would_increase_citation,
    ]),
  ]
  downloadCSV('optmizly-cite-tracker.csv', rows)
}

export function exportTrackerPDF(data: { overall_citation_score?: number; verdict?: string; results?: TrackerResult[] }) {
  const rows = (data.results ?? []).map(r => `
    <tr>
      <td>${r.query}</td>
      <td style="text-align:center"><strong>${r.citation_likelihood}</strong></td>
      <td><span class="badge ${r.citation_verdict}">${r.citation_verdict}</span></td>
      <td style="font-size:10px">${r.simulated_ai_response}</td>
      <td style="font-size:10px">${(r.reasons_for_citation ?? []).join('<br>')}</td>
      <td style="font-size:10px">${r.what_would_increase_citation}</td>
    </tr>`).join('')
  const html = `
    <h1>AI Citation Tracker Report</h1>
    <p class="meta">Generated by Optmizly · ${new Date().toLocaleDateString()}</p>
    <h2>Overall Citation Score: ${data.overall_citation_score ?? 0}/100</h2>
    <p>${data.verdict ?? ''}</p>
    <table>
      <thead><tr><th>Query</th><th>Score</th><th>Verdict</th><th>AI Response</th><th>Why Cited</th><th>How to Improve</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>`
  downloadPDF('Optmizly Cite Tracker Report', html)
}

// ─────────────────────────────────────────────────────────────────────────────
// LOCAL SEO EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

export function exportLocalCSV(data: Record<string, unknown>, subTool: string) {
  let rows: string[][] = []
  if (subTool === 'entities') {
    const d = data as { priority_additions?: Array<{ entity: string; type: string; why: string; example_sentence: string }> }
    rows = [
      ['Entity', 'Type', 'Why Important', 'Example Sentence'],
      ...(d.priority_additions ?? []).map(e => [e.entity, e.type, e.why, e.example_sentence]),
    ]
  } else if (subTool === 'queries') {
    const d = data as { queries?: Array<{ query: string; platform: string; intent_type: string; coverage_score: number; verdict: string; gap: string; fix: string }> }
    rows = [
      ['Query', 'Platform', 'Intent', 'Coverage Score', 'Verdict', 'Gap', 'Fix'],
      ...(d.queries ?? []).map(q => [q.query, q.platform, q.intent_type, String(q.coverage_score), q.verdict, q.gap, q.fix]),
    ]
  } else if (subTool === 'gbp') {
    const d = data as { gbp_posts?: Array<{ type: string; title: string; body: string; cta: string }>; qa_pairs?: Array<{ question: string; answer: string }> }
    rows = [
      ['Type', 'Title / Question', 'Body / Answer', 'CTA'],
      ...(d.gbp_posts ?? []).map(p => ['Post - ' + p.type, p.title, p.body, p.cta]),
      ...(d.qa_pairs ?? []).map(q => ['Q&A', q.question, q.answer, '']),
    ]
  } else {
    rows = [['Key', 'Value'], ...Object.entries(data).map(([k, v]) => [k, JSON.stringify(v)])]
  }
  downloadCSV(`optmizly-local-${subTool}.csv`, rows)
}

export function exportLocalPDF(data: Record<string, unknown>, subTool: string, city: string) {
  const toolLabels: Record<string, string> = {
    entities: 'Local Entity Analysis', nap: 'NAP + Schema Audit',
    queries: 'Local AI Query Map', gbp: 'GBP Content',
  }
  let content = ''
  if (subTool === 'entities') {
    const d = data as { local_entity_score?: number; summary?: string; priority_additions?: Array<{ entity: string; type: string; why: string; example_sentence: string }> }
    content = `<h2>Entity Score: ${d.local_entity_score ?? 0}/100</h2><p>${d.summary ?? ''}</p>
    <table><thead><tr><th>Entity</th><th>Type</th><th>Why Important</th><th>Example</th></tr></thead><tbody>
    ${(d.priority_additions ?? []).map(e => `<tr><td>${e.entity}</td><td>${e.type}</td><td>${e.why}</td><td><em>${e.example_sentence}</em></td></tr>`).join('')}
    </tbody></table>`
  } else if (subTool === 'nap') {
    const d = data as { nap_audit?: { name_found: boolean; address_found: boolean; phone_found: boolean; nap_score: number; consistency_issues: string[] }; json_ld?: string }
    content = `<h2>NAP Audit Score: ${d.nap_audit?.nap_score ?? 0}/100</h2>
    <p>Name: ${d.nap_audit?.name_found ? '✓' : '✗'} | Address: ${d.nap_audit?.address_found ? '✓' : '✗'} | Phone: ${d.nap_audit?.phone_found ? '✓' : '✗'}</p>
    ${d.nap_audit?.consistency_issues?.length ? `<h2>Issues</h2><ul>${d.nap_audit.consistency_issues.map(i => `<li>${i}</li>`).join('')}</ul>` : ''}
    ${d.json_ld ? `<h2>Generated JSON-LD Schema</h2><pre style="font-size:9px;background:#f8f8f8;padding:8px;border-radius:4px;overflow-wrap:break-word">${d.json_ld}</pre>` : ''}`
  } else if (subTool === 'queries') {
    const d = data as { queries?: Array<{ query: string; platform: string; verdict: string; coverage_score: number; fix: string }> }
    content = `<table><thead><tr><th>Query</th><th>Platform</th><th>Score</th><th>Verdict</th><th>Fix</th></tr></thead><tbody>
    ${(d.queries ?? []).map(q => `<tr><td>${q.query}</td><td>${q.platform}</td><td>${q.coverage_score}</td><td><span class="badge ${q.verdict}">${q.verdict}</span></td><td>${q.fix}</td></tr>`).join('')}
    </tbody></table>`
  } else if (subTool === 'gbp') {
    const d = data as { gbp_posts?: Array<{ type: string; title: string; body: string; cta: string; hashtags?: string[] }>; qa_pairs?: Array<{ question: string; answer: string }>; gbp_description?: string }
    content = `${d.gbp_description ? `<h2>GBP Description</h2><p>${d.gbp_description}</p>` : ''}
    <h2>Posts</h2>${(d.gbp_posts ?? []).map(p => `<p><strong>${p.type.toUpperCase()} — ${p.title}</strong><br>${p.body}<br><em>CTA: ${p.cta}</em></p>`).join('')}
    <h2>Q&amp;A Pairs</h2>${(d.qa_pairs ?? []).map(q => `<p><strong>Q: ${q.question}</strong><br>A: ${q.answer}</p>`).join('')}`
  }
  downloadPDF(`Optmizly Local SEO - ${toolLabels[subTool]}`, `
    <h1>Local SEO — ${toolLabels[subTool] ?? subTool}</h1>
    <p class="meta">Location: ${city} · Generated by Optmizly · ${new Date().toLocaleDateString()}</p>
    ${content}`)
}

// ─────────────────────────────────────────────────────────────────────────────
// SERP AUDIT EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type SerpData = {
  competitors?: Array<{ rank: number; url: string; authority: string; page_type: string; word_count: string; eeat: string }>
  root_causes?: Array<{ dimension: string; diagnosis: string; severity: string }>
  action_plan?: { phase1?: Array<{ task: string; why: string; effort: string; impact: string }>; phase2?: Array<{ task: string; why: string; effort: string; impact: string }>; phase3?: Array<{ task: string; why: string; effort: string; impact: string }> }
  rank_projection?: Array<{ month: string; position: number }>
  _meta?: { url: string; keyword: string; position?: string }
}

export function exportSerpCSV(data: SerpData) {
  const rows: string[][] = []
  rows.push(['SERP AUDIT REPORT'], ['Keyword', data._meta?.keyword ?? ''], ['Target URL', data._meta?.url ?? ''], [''])
  rows.push(['COMPETITORS'], ['Rank', 'URL', 'Authority', 'Page Type', 'Word Count', 'E-E-A-T'])
  ;(data.competitors ?? []).forEach(c => rows.push([String(c.rank), c.url, c.authority, c.page_type, c.word_count, c.eeat]))
  rows.push([''], ['ROOT CAUSES'], ['Dimension', 'Diagnosis', 'Severity'])
  ;(data.root_causes ?? []).forEach(rc => rows.push([rc.dimension, rc.diagnosis, rc.severity]))
  rows.push([''], ['ACTION PLAN — PHASE 1 (Weeks 1-4)'], ['Task', 'Why', 'Effort', 'Impact'])
  ;(data.action_plan?.phase1 ?? []).forEach(t => rows.push([t.task, t.why, t.effort, t.impact]))
  rows.push([''], ['ACTION PLAN — PHASE 2 (Weeks 5-10)'], ['Task', 'Why', 'Effort', 'Impact'])
  ;(data.action_plan?.phase2 ?? []).forEach(t => rows.push([t.task, t.why, t.effort, t.impact]))
  rows.push([''], ['RANK PROJECTION'], ['Month', 'Projected Position'])
  ;(data.rank_projection ?? []).forEach(r => rows.push([r.month, String(r.position)]))
  downloadCSV('optmizly-serp-audit.csv', rows)
}

export function exportSerpPDF(data: SerpData) {
  const compRows = (data.competitors ?? []).map(c => `
    <tr><td>${c.rank}</td><td style="font-size:10px">${c.url}</td><td>${c.authority}</td><td>${c.page_type}</td><td>${c.word_count}</td><td>${c.eeat}</td></tr>`).join('')
  const rcRows = (data.root_causes ?? []).map(rc => `
    <tr><td>${rc.dimension}</td><td>${rc.diagnosis}</td><td><span class="badge ${rc.severity}">${rc.severity}</span></td></tr>`).join('')
  const phaseTable = (items: Array<{ task: string; why: string; effort: string; impact: string }> = [], label: string) =>
    `<h2>${label}</h2><table><thead><tr><th>Task</th><th>Why</th><th>Effort</th><th>Impact</th></tr></thead><tbody>
    ${items.map(t => `<tr><td>${t.task}</td><td>${t.why}</td><td>${t.effort}</td><td><span class="badge ${t.impact}">${t.impact}</span></td></tr>`).join('')}</tbody></table>`
  const html = `
    <h1>SERP Competitor Audit</h1>
    <p class="meta">Keyword: <strong>${data._meta?.keyword ?? ''}</strong> · Target: ${data._meta?.url ?? ''} · Generated by Optmizly · ${new Date().toLocaleDateString()}</p>
    <h2>Top Competitors</h2>
    <table><thead><tr><th>#</th><th>URL</th><th>Authority</th><th>Page Type</th><th>Word Count</th><th>E-E-A-T</th></tr></thead><tbody>${compRows}</tbody></table>
    <h2>Root Causes</h2>
    <table><thead><tr><th>Dimension</th><th>Diagnosis</th><th>Severity</th></tr></thead><tbody>${rcRows}</tbody></table>
    ${phaseTable(data.action_plan?.phase1, 'Phase 1 — Weeks 1–4: Quick Wins')}
    ${phaseTable(data.action_plan?.phase2, 'Phase 2 — Weeks 5–10: Authority Building')}
    ${phaseTable(data.action_plan?.phase3, 'Phase 3 — Weeks 11–20: Content & Links')}
    ${data.rank_projection?.length ? `<h2>Rank Projection</h2><table><thead><tr><th>Month</th><th>Projected Position</th></tr></thead><tbody>
    ${data.rank_projection.map(r => `<tr><td>${r.month}</td><td>#${r.position}</td></tr>`).join('')}</tbody></table>` : ''}`
  downloadPDF('Optmizly SERP Audit', html)
}

// ─────────────────────────────────────────────────────────────────────────────
// TOPICAL AUTHORITY EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type TopicalPillar = {
  title: string; slug: string; monthly_searches: string; covered: boolean; ai_cite_score: number
  clusters: Array<{ title: string; slug: string; difficulty: string; monthly_searches: string; covered: boolean; primary_keyword: string }>
}

type TopicalData = {
  topic?: string; authority_score?: number; coverage_grade?: string
  pillar_pages?: TopicalPillar[]
  coverage_stats?: { total_topics: number; covered: number; missing: number; coverage_pct: number }
  content_calendar?: Array<{ week: number; title: string; type: string; why_now: string }>
}

export function exportTopicalCSV(data: TopicalData) {
  const rows: string[][] = []
  rows.push(['TOPICAL AUTHORITY MAP'], ['Niche', data.topic ?? ''], ['Authority Score', String(data.authority_score ?? 0)], ['Coverage Grade', data.coverage_grade ?? ''], [''])
  rows.push(['PILLAR & CLUSTER MAP'], ['Type', 'Title', 'Monthly Searches', 'Covered', 'Difficulty', 'AI Cite Score', 'Primary Keyword'])
  ;(data.pillar_pages ?? []).forEach(p => {
    rows.push(['PILLAR', p.title, p.monthly_searches, p.covered ? 'Yes' : 'No', '', String(p.ai_cite_score), ''])
    ;(p.clusters ?? []).forEach(c => rows.push(['  Cluster', c.title, c.monthly_searches, c.covered ? 'Yes' : 'No', c.difficulty, '', c.primary_keyword]))
  })
  rows.push([''], ['CONTENT CALENDAR'], ['Week', 'Title', 'Type', 'Why Now'])
  ;(data.content_calendar ?? []).forEach(c => rows.push([`Week ${c.week}`, c.title, c.type, c.why_now]))
  downloadCSV('optmizly-topical-authority.csv', rows)
}

export function exportTopicalPDF(data: TopicalData) {
  const pillarRows = (data.pillar_pages ?? []).flatMap(p => [
    `<tr style="background:#EFF6FF"><td colspan="5"><strong>${p.title}</strong></td><td>${p.monthly_searches}</td><td>${p.covered ? '✓' : '✗'}</td><td>${p.ai_cite_score}</td></tr>`,
    ...(p.clusters ?? []).map(c => `<tr><td style="padding-left:20px">↳ ${c.title}</td><td colspan="4" style="font-size:10px;color:#6b7280">${c.primary_keyword}</td><td>${c.monthly_searches}</td><td>${c.covered ? '✓' : '✗'}</td><td>${c.difficulty}</td></tr>`),
  ]).join('')
  const calRows = (data.content_calendar ?? []).map(c => `<tr><td>Week ${c.week}</td><td>${c.title}</td><td>${c.type}</td><td>${c.why_now}</td></tr>`).join('')
  const html = `
    <h1>Topical Authority Map</h1>
    <p class="meta">Niche: <strong>${data.topic ?? ''}</strong> · Generated by Optmizly · ${new Date().toLocaleDateString()}</p>
    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 12px 4px 0"><strong>Authority Score</strong></td><td>${data.authority_score ?? 0}/100</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Coverage Grade</strong></td><td>${data.coverage_grade ?? ''}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Total Topics</strong></td><td>${data.coverage_stats?.total_topics ?? 0} (${data.coverage_stats?.covered ?? 0} covered, ${data.coverage_stats?.missing ?? 0} missing)</td></tr>
    </table>
    <h2>Pillar & Cluster Map</h2>
    <table><thead><tr><th>Topic</th><th colspan="4"></th><th>Searches/mo</th><th>Covered</th><th>Score/Difficulty</th></tr></thead><tbody>${pillarRows}</tbody></table>
    ${calRows ? `<h2>Content Calendar</h2><table><thead><tr><th>Week</th><th>Title</th><th>Type</th><th>Why Now</th></tr></thead><tbody>${calRows}</tbody></table>` : ''}`
  downloadPDF('Optmizly Topical Authority', html)
}

// ─────────────────────────────────────────────────────────────────────────────
// SCORES (main dashboard) EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type AnalysisResult = {
  overall_score: number; grade: string; summary: string
  scores: Record<string, number>
  top_issues: Array<{ issue: string; impact: string; category: string; fix: string }>
  quick_wins: string[]; entity_gaps: string[]; llm_citation_tip: string
}

const SCORE_DIMS = [
  { key: 'technical_seo',          label: 'Technical SEO',      weight: '10%' },
  { key: 'on_page_seo',            label: 'On-Page SEO',        weight: '20%' },
  { key: 'entity_optimization',    label: 'Entity Optimization', weight: '15%' },
  { key: 'eeat_signals',           label: 'E-E-A-T Signals',    weight: '15%' },
  { key: 'semantic_richness',      label: 'Semantic Richness',   weight: '10%' },
  { key: 'llm_citation_triggers',  label: 'LLM Citation',       weight: '20%' },
  { key: 'structured_data',        label: 'Structured Data',    weight: '5%'  },
  { key: 'authority_reinforcement',label: 'Authority',          weight: '5%'  },
]

export function exportScoresCSV(data: AnalysisResult) {
  const rows: string[][] = [
    ['CONTENT ANALYSIS REPORT'],
    ['Overall Score', String(data.overall_score), 'Grade', data.grade],
    ['Summary', data.summary],
    [''],
    ['SCORE BREAKDOWN'],
    ['Dimension', 'Score', 'Weight'],
    ...SCORE_DIMS.map(d => [d.label, String(data.scores?.[d.key] ?? 0), d.weight]),
    [''],
    ['TOP ISSUES'],
    ['Issue', 'Impact', 'Category', 'Fix'],
    ...(data.top_issues ?? []).map(i => [i.issue, i.impact, i.category, i.fix]),
    [''],
    ['QUICK WINS'],
    ...(data.quick_wins ?? []).map(w => [w]),
    [''],
    ['MISSING ENTITIES'],
    ...(data.entity_gaps ?? []).map(e => [e]),
  ]
  downloadCSV('optmizly-scores.csv', rows)
}

export function exportScoresPDF(data: AnalysisResult) {
  const dimRows = SCORE_DIMS.map(d => {
    const v = data.scores?.[d.key] ?? 0
    const bar = '█'.repeat(Math.round(v / 10)) + '░'.repeat(10 - Math.round(v / 10))
    return `<tr><td>${d.label}</td><td style="font-family:monospace;font-size:10px;letter-spacing:-1px">${bar}</td><td style="text-align:right"><strong>${v}</strong>/100</td><td style="color:#6b7280;font-size:10px">${d.weight}</td></tr>`
  }).join('')
  const issueRows = (data.top_issues ?? []).map(i => `<tr><td>${i.issue}</td><td><span class="badge ${i.impact}">${i.impact}</span></td><td style="font-size:10px;color:#6b7280">${i.category}</td><td style="font-size:10px">${i.fix}</td></tr>`).join('')
  downloadPDF('Optmizly Content Score', `
    <h1>Content Analysis Report</h1>
    <p class="meta">Generated by Optmizly · ${new Date().toLocaleDateString()}</p>
    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 16px 4px 0"><strong>Overall Score</strong></td><td><span style="font-size:24px;font-weight:900">${data.overall_score}</span>/100</td><td style="padding-left:24px"><strong>Grade</strong></td><td style="font-size:24px;font-weight:900">${data.grade}</td></tr>
    </table>
    <p>${data.summary}</p>
    <h2>Score Breakdown</h2>
    <table><thead><tr><th>Dimension</th><th>Visual</th><th>Score</th><th>Weight</th></tr></thead><tbody>${dimRows}</tbody></table>
    <h2>Top Issues</h2>
    <table><thead><tr><th>Issue</th><th>Impact</th><th>Category</th><th>Fix</th></tr></thead><tbody>${issueRows}</tbody></table>
    <h2>Quick Wins</h2>
    <ul>${(data.quick_wins ?? []).map(w => `<li style="margin-bottom:4px">${w}</li>`).join('')}</ul>
    ${data.entity_gaps?.length ? `<h2>Missing Entities</h2><p>${data.entity_gaps.join(' · ')}</p>` : ''}
    ${data.llm_citation_tip ? `<h2>LLM Citation Tip</h2><p>${data.llm_citation_tip}</p>` : ''}`)
}

// ─────────────────────────────────────────────────────────────────────────────
// ISSUES EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type Issue = { issue: string; impact: string; category: string; fix: string }

export function exportIssuesCSV(issues: Issue[]) {
  downloadCSV('optmizly-issues.csv', [
    ['Issue', 'Impact', 'Category', 'Fix'],
    ...issues.map(i => [i.issue, i.impact, i.category, i.fix]),
  ])
}

export function exportIssuesPDF(issues: Issue[]) {
  const rows = issues.map(i => `<tr><td>${i.issue}</td><td><span class="badge ${i.impact}">${i.impact}</span></td><td style="color:#6b7280;font-size:10px">${i.category}</td><td style="font-size:10px">${i.fix}</td></tr>`).join('')
  downloadPDF('Optmizly Issues Audit', `
    <h1>Content Issues Audit</h1>
    <p class="meta">Generated by Optmizly · ${new Date().toLocaleDateString()} · ${issues.length} issues found</p>
    <table><thead><tr><th>Issue</th><th>Impact</th><th>Category</th><th>Fix</th></tr></thead><tbody>${rows}</tbody></table>`)
}

// ─────────────────────────────────────────────────────────────────────────────
// ENTITIES EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

export function exportEntitiesCSV(gaps: string[], wins: string[]) {
  downloadCSV('optmizly-entities.csv', [
    ['Type', 'Value'],
    ...gaps.map(e => ['Missing Entity', e]),
    ...wins.map(w => ['Quick Win', w]),
  ])
}

export function exportEntitiesPDF(gaps: string[], wins: string[]) {
  downloadPDF('Optmizly Entity Gaps', `
    <h1>Entity Gap Analysis</h1>
    <p class="meta">Generated by Optmizly · ${new Date().toLocaleDateString()}</p>
    <h2>Missing Entities (${gaps.length})</h2>
    <p>${gaps.map(e => `<span style="display:inline-block;background:#EDE9FE;color:#5B21B6;padding:2px 10px;border-radius:99px;margin:3px;font-size:11px">${e}</span>`).join('')}</p>
    <h2>Quick Wins (${wins.length})</h2>
    <ul>${wins.map(w => `<li style="margin-bottom:6px">${w}</li>`).join('')}</ul>`)
}

// ─────────────────────────────────────────────────────────────────────────────
// E-E-A-T EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type EEATData = {
  overall: number; summary: string
  dimensions: Record<string, { score: number; finding: string }>
  recommendations: string[]
}

export function exportEEATCSV(data: EEATData) {
  downloadCSV('optmizly-eeat.csv', [
    ['Overall E-E-A-T Score', String(data.overall)],
    ['Summary', data.summary ?? ''],
    [''],
    ['DIMENSIONS'],
    ['Dimension', 'Score', 'Finding'],
    ...Object.entries(data.dimensions ?? {}).map(([k, v]) => [
      k.charAt(0).toUpperCase() + k.slice(1), String(v.score), v.finding
    ]),
    [''],
    ['RECOMMENDATIONS'],
    ...(data.recommendations ?? []).map(r => [r]),
  ])
}

export function exportEEATPDF(data: EEATData) {
  const dimRows = Object.entries(data.dimensions ?? {}).map(([k, v]) => `
    <tr><td style="text-transform:capitalize;font-weight:600">${k}</td><td><strong>${v.score}/100</strong></td><td style="font-size:10px">${v.finding}</td></tr>`).join('')
  downloadPDF('Optmizly E-E-A-T Analysis', `
    <h1>E-E-A-T Analysis Report</h1>
    <p class="meta">Generated by Optmizly · ${new Date().toLocaleDateString()}</p>
    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 16px 4px 0"><strong>Overall E-E-A-T Score</strong></td><td style="font-size:28px;font-weight:900">${data.overall}/100</td></tr>
    </table>
    <p>${data.summary ?? ''}</p>
    <h2>Dimension Scores</h2>
    <table><thead><tr><th>Dimension</th><th>Score</th><th>Finding</th></tr></thead><tbody>${dimRows}</tbody></table>
    <h2>Recommendations</h2>
    <ol>${(data.recommendations ?? []).map(r => `<li style="margin-bottom:6px">${r}</li>`).join('')}</ol>`)
}

// ─────────────────────────────────────────────────────────────────────────────
// CITATION PLAN EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type CitationData = {
  summary?: string
  citation_opportunities?: Array<{ source_type: string; query: string; why: string; how_to_cite: string; priority: string }>
  citation_strategy?: string; schema_recommendations?: string[]
}

export function exportCitationCSV(data: CitationData) {
  downloadCSV('Optmizly-citation.csv', [
    ['Source Type', 'Target Query', 'Why This Matters', 'How to Cite', 'Priority'],
    ...(data.citation_opportunities ?? []).map(c => [c.source_type, c.query, c.why, c.how_to_cite, c.priority]),
    ...(data.schema_recommendations?.length ? [[''], ['SCHEMA RECOMMENDATIONS'], ...(data.schema_recommendations ?? []).map(r => [r])] : []),
  ])
}

export function exportCitationPDF(data: CitationData) {
  const rows = (data.citation_opportunities ?? []).map(c => `
    <tr><td>${c.source_type}</td><td>${c.query}</td><td style="font-size:10px">${c.why}</td><td style="font-size:10px">${c.how_to_cite}</td><td><span class="badge ${c.priority}">${c.priority}</span></td></tr>`).join('')
  downloadPDF('Optmizly Citation Plan', `
    <h1>AI Citation Plan</h1>
    <p class="meta">Generated by Optmizly · ${new Date().toLocaleDateString()}</p>
    ${data.summary ? `<p>${data.summary}</p>` : ''}
    ${data.citation_strategy ? `<h2>Strategy</h2><p>${data.citation_strategy}</p>` : ''}
    <h2>Citation Opportunities</h2>
    <table><thead><tr><th>Source</th><th>Query</th><th>Why</th><th>How to Cite</th><th>Priority</th></tr></thead><tbody>${rows}</tbody></table>
    ${data.schema_recommendations?.length ? `<h2>Schema Recommendations</h2><ul>${data.schema_recommendations.map(r => `<li>${r}</li>`).join('')}</ul>` : ''}`)
}

// ─────────────────────────────────────────────────────────────────────────────
// CONTENT GAP EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type GapData = {
  summary?: string
  gaps?: Array<{ title: string; why: string; opportunity: string; suggested_section: string }>
}

export function exportGapCSV(data: GapData) {
  downloadCSV('Optmizly-content-gap.csv', [
    ['Gap Topic', 'Why It Matters', 'Opportunity', 'Suggested Section'],
    ...(data.gaps ?? []).map(g => [g.title, g.why, g.opportunity, g.suggested_section]),
  ])
}

export function exportGapPDF(data: GapData) {
  const rows = (data.gaps ?? []).map(g => `
    <tr><td><strong>${g.title}</strong></td><td style="font-size:10px">${g.why}</td><td style="font-size:10px">${g.opportunity}</td><td style="font-size:10px;color:#6b7280">${g.suggested_section}</td></tr>`).join('')
  downloadPDF('Optmizly Content Gap Analysis', `
    <h1>Content Gap Analysis</h1>
    <p class="meta">Generated by Optmizly · ${new Date().toLocaleDateString()}</p>
    ${data.summary ? `<p>${data.summary}</p>` : ''}
    <table><thead><tr><th>Gap Topic</th><th>Why It Matters</th><th>Opportunity</th><th>Where to Add</th></tr></thead><tbody>${rows}</tbody></table>`)
}

// ─────────────────────────────────────────────────────────────────────────────
// AI QUERIES EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type QueriesData = {
  summary?: string
  queries?: Array<{ query: string; intent: string; coverage: string; why: string; fix: string }>
}

export function exportQueriesCSV(data: QueriesData) {
  downloadCSV('Optmizly-ai-queries.csv', [
    ['Query', 'Intent', 'Coverage', 'Why Important', 'Fix'],
    ...(data.queries ?? []).map(q => [q.query, q.intent, q.coverage, q.why, q.fix]),
  ])
}

export function exportQueriesPDF(data: QueriesData) {
  const rows = (data.queries ?? []).map(q => `
    <tr><td>${q.query}</td><td style="font-size:10px">${q.intent}</td><td><span class="badge ${q.coverage === 'covered' ? 'low' : q.coverage === 'partial' ? 'medium' : 'high'}">${q.coverage}</span></td><td style="font-size:10px">${q.fix}</td></tr>`).join('')
  downloadPDF('Optmizly AI Query Map', `
    <h1>AI Search Query Map</h1>
    <p class="meta">Generated by Optmizly · ${new Date().toLocaleDateString()}</p>
    ${data.summary ? `<p>${data.summary}</p>` : ''}
    <table><thead><tr><th>Query</th><th>Intent</th><th>Coverage</th><th>Fix</th></tr></thead><tbody>${rows}</tbody></table>`)
}

// ─────────────────────────────────────────────────────────────────────────────
// ON-PAGE SEO EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type OnPageData = {
  id: string; targetKeyword: string; pageUrl?: string; pageTitle?: string
  overallScore: number; previousScore?: number; wordCount: number
  keywordScore: number; headerScore: number; metaScore: number
  imageScore: number; linkScore: number; readabilityScore: number
  keywordDensity: number; keywordCount: number
  keywordData: { count: number; density: number; inFirstParagraph: boolean; inLastParagraph: boolean; issues: string[] }
  headers: { h1: string[]; h2: string[]; h3: string[]; hasKeywordInH1: boolean; issues: string[] }
  metaTags: { title?: string; description?: string; titleHasKeyword: boolean; descHasKeyword: boolean; issues: string[] }
  images: { total: number; withAlt: number; withKeywordInAlt: number; issues: string[] }
  links: { internal: number; external: number; issues: string[] }
  readabilityData: { avgSentenceLength: number; paragraphCount: number; issues: string[] }
  fixes: Array<{ category: string; priority: string; issue: string; suggestion: string; before?: string; after?: string }>
  appliedFixes: number[]
  analyzedAt: string
}

export function exportOnPageCSV(data: OnPageData) {
  const rows: string[][] = []
  rows.push(['ON-PAGE SEO ANALYSIS REPORT'])
  rows.push(['Target Keyword', data.targetKeyword])
  rows.push(['Page URL', data.pageUrl ?? ''])
  rows.push(['Page Title', data.pageTitle ?? ''])
  rows.push(['Date', new Date(data.analyzedAt).toLocaleDateString()])
  rows.push([''])

  rows.push(['OVERALL SCORE', String(data.overallScore), '/100'])
  if (data.previousScore !== undefined && data.previousScore !== null) {
    const delta = data.overallScore - data.previousScore
    rows.push(['Previous Score', String(data.previousScore), `${delta >= 0 ? '+' : ''}${delta}`])
  }
  rows.push(['Word Count', String(data.wordCount)])
  rows.push([''])

  rows.push(['CATEGORY SCORES'])
  rows.push(['Category', 'Score', 'Weight'])
  const categories = [
    { key: 'keywordScore', label: 'Keyword', weight: '25%' },
    { key: 'headerScore', label: 'Headers', weight: '20%' },
    { key: 'metaScore', label: 'Meta Tags', weight: '20%' },
    { key: 'imageScore', label: 'Images', weight: '10%' },
    { key: 'linkScore', label: 'Links', weight: '10%' },
    { key: 'readabilityScore', label: 'Readability', weight: '15%' },
  ]
  categories.forEach(cat => {
    const score = data[cat.key as keyof OnPageData] as number
    rows.push([cat.label, String(score), cat.weight])
  })
  rows.push([''])

  rows.push(['KEYWORD ANALYSIS'])
  rows.push(['Metric', 'Value'])
  rows.push(['Keyword Count', String(data.keywordCount)])
  rows.push(['Keyword Density', `${data.keywordDensity.toFixed(2)}%`])
  rows.push(['In First Paragraph', data.keywordData.inFirstParagraph ? 'Yes' : 'No'])
  rows.push(['In Last Paragraph', data.keywordData.inLastParagraph ? 'Yes' : 'No'])
  if (data.keywordData.issues.length) {
    rows.push(['Issues', data.keywordData.issues.join('; ')])
  }
  rows.push([''])

  rows.push(['HEADERS'])
  rows.push(['Type', 'Count', 'Keyword Present'])
  rows.push(['H1', String(data.headers.h1.length), data.headers.hasKeywordInH1 ? 'Yes' : 'No'])
  rows.push(['H2', String(data.headers.h2.length), ''])
  rows.push(['H3', String(data.headers.h3.length), ''])
  if (data.headers.issues.length) {
    rows.push(['Issues', data.headers.issues.join('; ')])
  }
  rows.push([''])

  rows.push(['META TAGS'])
  rows.push(['Tag', 'Value', 'Has Keyword'])
  rows.push(['Title', data.metaTags.title ?? '', data.metaTags.titleHasKeyword ? 'Yes' : 'No'])
  rows.push(['Description', data.metaTags.description ?? '', data.metaTags.descHasKeyword ? 'Yes' : 'No'])
  if (data.metaTags.issues.length) {
    rows.push(['Issues', data.metaTags.issues.join('; ')])
  }
  rows.push([''])

  rows.push(['IMAGES'])
  rows.push(['Metric', 'Value'])
  rows.push(['Total Images', String(data.images.total)])
  rows.push(['With Alt Text', String(data.images.withAlt)])
  rows.push(['With Keyword in Alt', String(data.images.withKeywordInAlt)])
  if (data.images.issues.length) {
    rows.push(['Issues', data.images.issues.join('; ')])
  }
  rows.push([''])

  rows.push(['LINKS'])
  rows.push(['Type', 'Count'])
  rows.push(['Internal Links', String(data.links.internal)])
  rows.push(['External Links', String(data.links.external)])
  if (data.links.issues.length) {
    rows.push(['Issues', data.links.issues.join('; ')])
  }
  rows.push([''])

  rows.push(['READABILITY'])
  rows.push(['Metric', 'Value'])
  rows.push(['Avg Sentence Length', String(data.readabilityData.avgSentenceLength)])
  rows.push(['Paragraph Count', String(data.readabilityData.paragraphCount)])
  if (data.readabilityData.issues.length) {
    rows.push(['Issues', data.readabilityData.issues.join('; ')])
  }
  rows.push([''])

  rows.push(['RECOMMENDATIONS'])
  rows.push(['Priority', 'Category', 'Issue', 'Suggestion', 'Applied'])
  data.fixes.forEach((fix, idx) => {
    rows.push([fix.priority.toUpperCase(), fix.category, fix.issue, fix.suggestion, data.appliedFixes.includes(idx) ? 'Yes' : 'No'])
  })

  downloadCSV('Optmizly-onpage.csv', rows)
}

export function exportOnPagePDF(data: OnPageData) {
  const categoryRows = [
    { key: 'keywordScore', label: 'Keyword', weight: '25%' },
    { key: 'headerScore', label: 'Headers', weight: '20%' },
    { key: 'metaScore', label: 'Meta Tags', weight: '20%' },
    { key: 'imageScore', label: 'Images', weight: '10%' },
    { key: 'linkScore', label: 'Links', weight: '10%' },
    { key: 'readabilityScore', label: 'Readability', weight: '15%' },
  ].map(cat => {
    const score = data[cat.key as keyof OnPageData] as number
    const bar = '█'.repeat(Math.round(score / 10)) + '░'.repeat(10 - Math.round(score / 10))
    return `<tr><td>${cat.label}</td><td style="font-family:monospace;font-size:10px;letter-spacing:-1px">${bar}</td><td style="text-align:right"><strong>${score}</strong>/100</td><td style="color:#6b7280;font-size:9px">${cat.weight}</td></tr>`
  }).join('')

  const fixRows = data.fixes.map((fix, idx) => `<tr><td><span class="badge ${fix.priority}">${fix.priority.toUpperCase()}</span></td><td>${fix.category}</td><td>${fix.issue}</td><td style="font-size:10px">${fix.suggestion}</td><td style="text-align:center">${data.appliedFixes.includes(idx) ? '✓' : ''}</td></tr>`).join('')

  downloadPDF('Optmizly On-Page SEO Analysis', `
    <h1>On-Page SEO Analysis</h1>
    <p class="meta">Keyword: <strong>${data.targetKeyword}</strong> · URL: ${data.pageUrl ?? ''} · Generated by Optmizly · ${new Date(data.analyzedAt).toLocaleDateString()}</p>
    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 16px 4px 0"><strong>Overall Score</strong></td><td style="font-size:24px;font-weight:900">${data.overallScore}</span>/100</td>${data.previousScore !== undefined && data.previousScore !== null ? `<td style="padding-left:24px;color:${data.overallScore >= data.previousScore ? '#16a34a' : '#dc2626'};font-weight:600">${data.overallScore >= data.previousScore ? '+' : ''}${data.overallScore - data.previousScore}</td>` : ''}</tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Word Count</strong></td><td>${data.wordCount}</td></tr>
    </table>
    <h2>Category Scores</h2>
    <table><thead><tr><th>Category</th><th style="width:100px">Score</th><th>Value</th><th style="width:50px">Weight</th></tr></thead><tbody>${categoryRows}</tbody></table>
    <h2>Keyword Analysis</h2>
    <table style="width:auto">
      <tr><td style="padding:4px 12px 4px 0"><strong>Keyword Count</strong></td><td>${data.keywordCount}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Keyword Density</strong></td><td>${data.keywordDensity.toFixed(2)}%</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>In First Paragraph</strong></td><td>${data.keywordData.inFirstParagraph ? '✓' : '✗'}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>In Last Paragraph</strong></td><td>${data.keywordData.inLastParagraph ? '✓' : '✗'}</td></tr>
    </table>
    ${data.keywordData.issues.length ? `<h3>Issues</h3><ul>${data.keywordData.issues.map(i => `<li style="font-size:10px">${i}</li>`).join('')}</ul>` : ''}
    <h2>Meta Tags</h2>
    <table style="width:auto;margin-bottom:12px">
      <tr><td style="padding:4px 12px 4px 0"><strong>Title</strong></td><td style="font-size:10px">${data.metaTags.title ?? '(none)'}</td><td style="text-align:center">${data.metaTags.titleHasKeyword ? '✓' : '✗'}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Description</strong></td><td style="font-size:10px">${data.metaTags.description ?? '(none)'}</td><td style="text-align:center">${data.metaTags.descHasKeyword ? '✓' : '✗'}</td></tr>
    </table>
    ${data.metaTags.issues.length ? `<p style="color:#6b7280;font-size:10px">${data.metaTags.issues.join(' · ')}</p>` : ''}
    <h2>Headers</h2>
    <table style="width:auto">
      <tr><td style="padding:4px 12px 4px 0"><strong>H1 Tags</strong></td><td>${data.headers.h1.length}</td><td style="text-align:center;font-size:10px">${data.headers.hasKeywordInH1 ? '✓ Keyword' : '✗ No keyword'}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>H2 Tags</strong></td><td>${data.headers.h2.length}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>H3 Tags</strong></td><td>${data.headers.h3.length}</td></tr>
    </table>
    <h2>Images & Links</h2>
    <table style="width:auto">
      <tr><td style="padding:4px 12px 4px 0"><strong>Total Images</strong></td><td>${data.images.total}</td><td style="padding-left:24px"><strong>Internal Links</strong></td><td>${data.links.internal}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>With Alt Text</strong></td><td>${data.images.withAlt}</td><td style="padding-left:24px"><strong>External Links</strong></td><td>${data.links.external}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Keyword in Alt</strong></td><td>${data.images.withKeywordInAlt}</td></tr>
    </table>
    <h2>Readability</h2>
    <table style="width:auto">
      <tr><td style="padding:4px 12px 4px 0"><strong>Avg Sentence Length</strong></td><td>${data.readabilityData.avgSentenceLength} words</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Paragraphs</strong></td><td>${data.readabilityData.paragraphCount}</td></tr>
    </table>
    <h2>Recommendations (${data.fixes.length})</h2>
    <table><thead><tr><th>Priority</th><th>Category</th><th>Issue</th><th>Suggestion</th><th style="text-align:center">Applied</th></tr></thead><tbody>${fixRows}</tbody></table>`)
}

// ─────────────────────────────────────────────────────────────────────────────
// SEO AUDIT EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type SeoAuditData = {
  url: string; pageTitle: string | null; createdAt: string
  overallScore: number; totalChecks: number
  passedChecks: number; failedChecks: number; warnChecks: number
  categoryScores: Record<string, number>
  autoResults: Record<string, { status: string; detail: string }>
  aiResults: Record<string, { score: number; issues: string[]; fixes: string[] }>
  checklistState: Record<string, string>
  backlinkData?: { oprScore: number | null; domainRank: number | null }
}

export function exportSeoAuditCSV(data: SeoAuditData) {
  const catMap = Object.fromEntries(AUDIT_FRAMEWORK.map(c => [c.key, c.title]))
  const rows: string[][] = []

  rows.push(['ENTERPRISE SEO AUDIT REPORT'])
  rows.push(['URL', data.url])
  rows.push(['Page Title', data.pageTitle ?? ''])
  rows.push(['Date', new Date(data.createdAt).toLocaleDateString()])
  rows.push([''])

  rows.push(['OVERALL SCORE', String(data.overallScore), '/100'])
  rows.push(['Passed Checks', String(data.passedChecks), `of ${data.totalChecks}`])
  rows.push(['Warning Checks', String(data.warnChecks)])
  rows.push(['Failed Checks', String(data.failedChecks)])
  if (data.backlinkData?.oprScore != null) {
    rows.push(['Domain Authority (OPR)', data.backlinkData.oprScore.toFixed(1), '/10'])
    if (data.backlinkData.domainRank && data.backlinkData.domainRank > 0) {
      rows.push(['Global Domain Rank', `#${data.backlinkData.domainRank.toLocaleString()}`])
    }
  }
  rows.push([''])

  rows.push(['CATEGORY SCORES'])
  rows.push(['Category', 'Score', 'Priority', 'Tag'])
  Object.entries(data.categoryScores).forEach(([key, score]) => {
    const cat = AUDIT_FRAMEWORK.find(c => c.key === key)
    if (cat) rows.push([cat.title, String(score), cat.priority, cat.tag])
  })
  rows.push([''])

  rows.push(['AUTO-DETECTED ISSUES (Fails & Warnings)'])
  rows.push(['Check ID', 'Label', 'Status', 'Detail'])
  Object.entries(data.autoResults).forEach(([id, result]) => {
    if (result.status === 'fail' || result.status === 'warn') {
      const cat = AUDIT_FRAMEWORK.flatMap(c => c.subCategories.flatMap(s => s.checks)).find(c => c.id === id)
      rows.push([id, cat?.label ?? '', result.status.toUpperCase(), result.detail])
    }
  })
  rows.push([''])

  rows.push(['AI ASSESSMENTS'])
  rows.push(['Category', 'Score', 'Top Issues', 'Top Fixes'])
  Object.entries(data.aiResults).forEach(([key, result]) => {
    const cat = AUDIT_FRAMEWORK.find(c => c.key === key)
    if (cat) {
      rows.push([
        cat.title,
        String(result.score),
        (result.issues ?? []).slice(0, 2).join(' | '),
        (result.fixes ?? []).slice(0, 2).join(' | ')
      ])
    }
  })
  rows.push([''])

  rows.push(['MANUAL CHECKLIST (User-Set Items)'])
  rows.push(['Check ID', 'Label', 'Status'])
  Object.entries(data.checklistState).forEach(([id, status]) => {
    const cat = AUDIT_FRAMEWORK.flatMap(c => c.subCategories.flatMap(s => s.checks)).find(c => c.id === id)
    if (cat) rows.push([id, cat.label, status.toUpperCase()])
  })

  downloadCSV('Optmizly-seo-audit.csv', rows)
}

export function exportSeoAuditPDF(data: SeoAuditData) {
  const categoryRows = AUDIT_FRAMEWORK.map(cat => {
    const score = data.categoryScores[cat.key] ?? 0
    const bar = '█'.repeat(Math.round(score / 10)) + '░'.repeat(10 - Math.round(score / 10))
    return `<tr><td style="font-weight:600">${cat.title}</td><td style="font-family:monospace;font-size:10px;letter-spacing:-1px">${bar}</td><td style="text-align:right"><strong>${score}</strong>/100</td><td style="color:#6b7280;font-size:9px">${cat.priority}</td></tr>`
  }).join('')

  const aiSections = Object.entries(data.aiResults).map(([key, result]) => {
    const cat = AUDIT_FRAMEWORK.find(c => c.key === key)
    if (!cat || !result.issues.length && !result.fixes.length) return ''
    return `<h3 style="color:#1e3a8a;margin:12px 0 6px;font-size:12px;font-weight:600">${cat.title}</h3>
    <p style="color:#6b7280;font-size:10px;margin:0 0 6px 0"><strong>Score: ${result.score}/100</strong></p>
    ${result.issues.length ? `<div style="margin-bottom:6px"><span style="font-weight:600;color:#dc2626;font-size:10px">Issues:</span><ul style="margin:4px 0;padding-left:20px">${result.issues.map(i => `<li style="font-size:10px;margin:2px 0">${i}</li>`).join('')}</ul></div>` : ''}
    ${result.fixes.length ? `<div><span style="font-weight:600;color:#16a34a;font-size:10px">Fixes:</span><ul style="margin:4px 0;padding-left:20px">${result.fixes.map(f => `<li style="font-size:10px;margin:2px 0">${f}</li>`).join('')}</ul></div>` : ''}`
  }).filter(Boolean).join('')

  const autoFailWarn = Object.entries(data.autoResults)
    .filter(([, r]) => r.status === 'fail' || r.status === 'warn')
    .map(([id, result]) => {
      const cat = AUDIT_FRAMEWORK.flatMap(c => c.subCategories.flatMap(s => s.checks)).find(c => c.id === id)
      return `<tr><td style="font-size:10px">${cat?.label ?? id}</td><td><span class="badge ${result.status}">${result.status.toUpperCase()}</span></td><td style="font-size:9px;color:#6b7280">${result.detail}</td></tr>`
    }).join('')

  const manualRows = Object.entries(data.checklistState)
    .map(([id, status]) => {
      const cat = AUDIT_FRAMEWORK.flatMap(c => c.subCategories.flatMap(s => s.checks)).find(c => c.id === id)
      return `<tr><td style="font-size:10px">${cat?.label ?? id}</td><td><span class="badge ${status}">${status.toUpperCase()}</span></td></tr>`
    }).join('')

  downloadPDF('Optmizly Enterprise SEO Audit', `
    <h1>Enterprise SEO Audit Report</h1>
    <p class="meta">URL: ${data.url} · Generated by Optmizly · ${new Date(data.createdAt).toLocaleDateString()}</p>
    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 16px 4px 0"><strong>Overall Score</strong></td><td style="font-size:24px;font-weight:900">${data.overallScore}</span>/100</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Results</strong></td><td style="font-size:11px">✓ ${data.passedChecks} passed · ⚠ ${data.warnChecks} warnings · ✗ ${data.failedChecks} failed</td></tr>
      ${data.backlinkData?.oprScore != null ? `<tr><td style="padding:4px 16px 4px 0"><strong>Domain Authority</strong></td><td>OPR Score: <strong>${data.backlinkData.oprScore.toFixed(1)}/10</strong>${data.backlinkData.domainRank && data.backlinkData.domainRank > 0 ? ` · Global Rank: <strong>#${data.backlinkData.domainRank.toLocaleString()}</strong>` : ''}</td></tr>` : ''}
    </table>
    <h2>Category Breakdown</h2>
    <table><thead><tr><th>Category</th><th style="width:100px">Score</th><th>Value</th><th style="width:50px">Priority</th></tr></thead><tbody>${categoryRows}</tbody></table>
    ${aiSections ? `<h2>AI Assessments</h2><div style="background:#f8fafc;padding:12px;border-radius:6px;border-left:4px solid #2563eb">${aiSections}</div>` : ''}
    ${autoFailWarn ? `<h2>Auto-Detected Issues</h2><table><thead><tr><th>Issue</th><th>Status</th><th style="width:300px">Detail</th></tr></thead><tbody>${autoFailWarn}</tbody></table>` : ''}
    ${manualRows ? `<h2>Manual Checklist</h2><table><thead><tr><th>Check</th><th>Status</th></tr></thead><tbody>${manualRows}</tbody></table>` : ''}`)
}

// ─────────────────────────────────────────────────────────────────────────────
// PERFORMANCE FIXER EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type PerformanceFixerData = {
  url: string; createdAt?: string
  metrics: {
    overallScore: number; lcpScore: number; clsScore: number; fidScore: number | null; inpScore: number | null
    lcp: number; cls: number; fid: number | null; inp: number | null
    fcp: number | null; fcpScore: number | null; speedIndex: number | null; speedIndexScore: number | null
    tti: number | null; ttiScore: number | null; tbt: number | null; tbtScore: number | null
    ttfb: number | null; ttfbScore: number | null; unusedJs: number | null; unusedJsScore: number | null
    unusedCss: number | null; unusedCssScore: number | null; renderBlockingScore: number | null
    redirects: number | null; redirectsScore: number | null; jsBootupTime: number | null; jsBootupScore: number | null
    legacyJsScore: number | null; totalByteWeight: number | null
    domSize?: number | null; mainthreadWork?: number | null; networkRtt?: number | null
  }
  projectedScore: number
  fixes: Array<{ type: string; issue: string; beforeCode: string; afterCode: string; description: string; estimatedImpact: number; language: string }>
  roi?: { currentRevenueLoss: number; potentialRevenue: number; fixTime: number; estimatedCost: number } | null
  industryData?: { avg: number; topPercent: number; rank: number } | null
}

export function exportPerformanceFixerCSV(data: PerformanceFixerData) {
  const rows: string[][] = []

  rows.push(['AI PERFORMANCE FIXER REPORT'])
  rows.push(['URL', data.url])
  rows.push(['Date', data.createdAt ? new Date(data.createdAt).toLocaleDateString() : new Date().toLocaleDateString()])
  rows.push([''])

  rows.push(['PERFORMANCE SCORE'])
  rows.push(['Current Score', String(data.metrics.overallScore), '/100'])
  rows.push(['Projected Score (After Fixes)', String(data.projectedScore), '/100'])
  rows.push(['Potential Improvement', String(data.projectedScore - data.metrics.overallScore), 'points'])
  rows.push([''])

  rows.push(['CORE WEB VITALS'])
  rows.push(['Metric', 'Value', 'Score'])
  rows.push(['LCP (Largest Contentful Paint)', `${data.metrics.lcp.toFixed(2)}s`, String(data.metrics.lcpScore)])
  rows.push(['CLS (Cumulative Layout Shift)', data.metrics.cls.toFixed(3), String(data.metrics.clsScore)])
  if (data.metrics.fid !== null) rows.push(['FID (First Input Delay)', `${Math.round(data.metrics.fid)}ms`, String(data.metrics.fidScore)])
  if (data.metrics.inp !== null) rows.push(['INP (Interaction to Next Paint)', `${Math.round(data.metrics.inp)}ms`, String(data.metrics.inpScore)])
  rows.push([''])

  rows.push(['ADDITIONAL METRICS'])
  rows.push(['Metric', 'Value', 'Score'])
  if (data.metrics.fcp !== null) rows.push(['FCP (First Contentful Paint)', `${data.metrics.fcp.toFixed(2)}s`, String(data.metrics.fcpScore)])
  if (data.metrics.speedIndex !== null) rows.push(['Speed Index', `${data.metrics.speedIndex.toFixed(2)}s`, String(data.metrics.speedIndexScore)])
  if (data.metrics.tti !== null) rows.push(['TTI (Time to Interactive)', `${data.metrics.tti.toFixed(2)}s`, String(data.metrics.ttiScore)])
  if (data.metrics.tbt !== null) rows.push(['TBT (Total Blocking Time)', `${Math.round(data.metrics.tbt)}ms`, String(data.metrics.tbtScore)])
  if (data.metrics.ttfb !== null) rows.push(['TTFB (Time to First Byte)', `${Math.round(data.metrics.ttfb)}ms`, String(data.metrics.ttfbScore)])
  rows.push([''])

  rows.push(['OPPORTUNITIES & DIAGNOSTICS'])
  rows.push(['Opportunity', 'Value', 'Score'])
  if (data.metrics.unusedJs !== null) rows.push(['Unused JavaScript', `${Math.round(data.metrics.unusedJs / 1024)} KB`, String(data.metrics.unusedJsScore)])
  if (data.metrics.unusedCss !== null) rows.push(['Unused CSS', `${Math.round(data.metrics.unusedCss / 1024)} KB`, String(data.metrics.unusedCssScore)])
  rows.push(['Render Blocking Resources', '', String(data.metrics.renderBlockingScore)])
  if (data.metrics.redirects !== null) rows.push(['Redirects', `${Math.round(data.metrics.redirects)}ms`, String(data.metrics.redirectsScore)])
  if (data.metrics.jsBootupTime !== null) rows.push(['JS Bootup Time', `${Math.round(data.metrics.jsBootupTime)}ms`, String(data.metrics.jsBootupScore)])
  rows.push(['Legacy JavaScript', '', String(data.metrics.legacyJsScore)])
  if (data.metrics.totalByteWeight !== null) rows.push(['Page Weight', `${Math.round(data.metrics.totalByteWeight / 1024)} KB`, ''])
  rows.push([''])

  if (data.industryData) {
    rows.push(['INDUSTRY BENCHMARKS'])
    rows.push(['Industry Average', String(Math.round(data.industryData.avg))])
    rows.push(['Top 25% Performers', String(Math.round(data.industryData.topPercent))])
    rows.push(['Your Rank', String(data.industryData.rank)])
    rows.push([''])
  }

  if (data.roi) {
    rows.push(['ROI & IMPACT'])
    rows.push(['Current Revenue Loss / Month', `$${data.roi.currentRevenueLoss.toLocaleString()}`])
    rows.push(['Potential Revenue / Month', `$${data.roi.potentialRevenue.toLocaleString()}`])
    rows.push(['Est. Fix Time', `${data.roi.fixTime} hours`])
    rows.push(['Est. Implementation Cost', `$${data.roi.estimatedCost.toLocaleString()}`])
    rows.push([''])
  }

  rows.push(['RECOMMENDED FIXES (Count: ' + data.fixes.length + ')'])
  rows.push(['#', 'Issue', 'Impact', 'Type', 'Description'])
  data.fixes.forEach((fix, idx) => {
    rows.push([
      String(idx + 1),
      fix.issue,
      `+${fix.estimatedImpact} pts`,
      fix.type,
      fix.description
    ])
  })

  downloadCSV('Optmizly-performance-fixer.csv', rows)
}

export function exportPerformanceFixerPDF(data: PerformanceFixerData) {
  const gain = data.projectedScore - data.metrics.overallScore
  const metricsRows = [
    { label: 'LCP', value: `${data.metrics.lcp.toFixed(2)}s`, score: data.metrics.lcpScore, good: data.metrics.lcpScore !== null && data.metrics.lcpScore >= 75 },
    { label: 'CLS', value: data.metrics.cls.toFixed(3), score: data.metrics.clsScore, good: data.metrics.clsScore !== null && data.metrics.clsScore >= 75 },
    data.metrics.fid !== null && data.metrics.fidScore !== null ? { label: 'FID', value: `${Math.round(data.metrics.fid)}ms`, score: data.metrics.fidScore, good: data.metrics.fidScore >= 75 } : null,
    data.metrics.inp !== null && data.metrics.inpScore !== null ? { label: 'INP', value: `${Math.round(data.metrics.inp)}ms`, score: data.metrics.inpScore, good: data.metrics.inpScore >= 75 } : null,
  ].filter(Boolean) as Array<{ label: string; value: string; score: number; good: boolean }>

  const fixRows = data.fixes.map((fix, idx) => `
    <tr>
      <td style="font-weight:600">${idx + 1}. ${fix.issue}</td>
      <td style="text-align:right"><strong>+${fix.estimatedImpact}</strong></td>
      <td><span class="badge ${fix.estimatedImpact >= 20 ? 'high' : fix.estimatedImpact >= 10 ? 'medium' : 'low'}">${fix.type}</span></td>
      <td style="font-size:10px;color:#6b7280">${fix.description}</td>
    </tr>`).join('')

  const html = `
    <h1>AI Performance Fixer Report</h1>
    <p class="meta">URL: ${data.url} · Generated by Optmizly · ${data.createdAt ? new Date(data.createdAt).toLocaleDateString() : new Date().toLocaleDateString()}</p>

    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 16px 4px 0"><strong>Current Score</strong></td><td style="font-size:24px;font-weight:900;color:#f59e0b">${data.metrics.overallScore}</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>After Fixes</strong></td><td style="font-size:24px;font-weight:900;color:#10b981">${data.projectedScore}</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Improvement</strong></td><td style="font-size:20px;font-weight:900;color:#3b82f6">+${gain}</td></tr>
    </table>

    <h2>Core Web Vitals</h2>
    <table><thead><tr><th>Metric</th><th style="width:60px">Value</th><th style="width:60px">Score</th></tr></thead><tbody>${metricsRows.map(m => `<tr><td>${m.label}</td><td>${m.value}</td><td><span class="badge ${m.good ? 'low' : m.score >= 50 ? 'medium' : 'high'}">${m.score}/100</span></td></tr>`).join('')}</tbody></table>

    <h2>Recommended Fixes (${data.fixes.length} total)</h2>
    <table><thead><tr><th>Issue</th><th style="text-align:right;width:50px">Impact</th><th style="width:80px">Type</th><th style="width:300px">Description</th></tr></thead><tbody>${fixRows}</tbody></table>

    ${data.roi ? `<h2>ROI & Business Impact</h2>
    <table style="width:auto">
      <tr><td style="padding:4px 12px 4px 0"><strong>Current Revenue Loss/Mo</strong></td><td>$${data.roi.currentRevenueLoss.toLocaleString()}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Potential Revenue/Mo</strong></td><td>$${data.roi.potentialRevenue.toLocaleString()}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Est. Fix Time</strong></td><td>${data.roi.fixTime} hours</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Est. Implementation Cost</strong></td><td>$${data.roi.estimatedCost.toLocaleString()}</td></tr>
    </table>` : ''}

    ${data.industryData ? `<h2>Industry Benchmarks</h2>
    <table style="width:auto">
      <tr><td style="padding:4px 12px 4px 0"><strong>Industry Average</strong></td><td>${Math.round(data.industryData.avg)}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Top 25%</strong></td><td>${Math.round(data.industryData.topPercent)}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Your Rank</strong></td><td>${data.industryData.rank}</td></tr>
    </table>` : ''}`

  downloadPDF('Optmizly Performance Fixer Report', html)
}

// ─────────────────────────────────────────────────────────────────────────────
// COMPETITOR SPY EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type Keyword = { keyword: string; position: number; volume: number; traffic: number }
type BacklinkSource = { domain: string; links: number; da: number }
type Page = { title: string; url: string; traffic: number }
type GapKeyword = { keyword: string; volume: number; difficulty: number }
type ContentOpp = { title: string; opportunity: string; traffic: number }
type AIInsights = { strengths?: string[]; weaknesses?: string[]; topOpportunity?: string; threatLevel?: string }

type CompetitorSpyData = {
  id: string
  domainName: string
  domainUrl: string
  estimatedTraffic: number
  domainAuthority: number
  pageAuthority: number
  backlinksTotal: number
  backlinksNew: number
  keywordCount: number
  contentCount: number
  avgContentLength: number
  topKeywords: Keyword[]
  topPages: Page[]
  topBacklinks: BacklinkSource[]
  gapKeywords: GapKeyword[]
  missingEntities: string[]
  contentOpps: ContentOpp[]
  aiInsights: AIInsights | null
  lastAnalyzedAt: string
}

export function exportCompetitorSpyCSV(data: CompetitorSpyData) {
  const rows: string[][] = []

  rows.push(['COMPETITOR ANALYSIS REPORT'])
  rows.push(['Domain', data.domainName])
  rows.push(['URL', data.domainUrl])
  rows.push(['Date', new Date(data.lastAnalyzedAt).toLocaleDateString()])
  rows.push([''])

  rows.push(['KEY METRICS'])
  rows.push(['Metric', 'Value'])
  rows.push(['Estimated Monthly Traffic', String(data.estimatedTraffic.toLocaleString())])
  rows.push(['Domain Authority', String(data.domainAuthority)])
  rows.push(['Page Authority', String(data.pageAuthority)])
  rows.push(['Total Backlinks', String(data.backlinksTotal.toLocaleString())])
  rows.push(['New Backlinks', String(data.backlinksNew.toLocaleString())])
  rows.push(['Keywords Ranked', String(data.keywordCount.toLocaleString())])
  rows.push(['Content Count', String(data.contentCount)])
  rows.push(['Avg Content Length', String(data.avgContentLength) + ' words'])
  rows.push([''])

  if (data.aiInsights?.threatLevel) {
    rows.push(['THREAT ASSESSMENT'])
    rows.push(['Threat Level', data.aiInsights.threatLevel.toUpperCase()])
    rows.push([''])
  }

  rows.push(['STRENGTHS'])
  if (data.aiInsights?.strengths && data.aiInsights.strengths.length > 0) {
    data.aiInsights.strengths.forEach(s => rows.push([s]))
  }
  rows.push([''])

  rows.push(['WEAKNESSES'])
  if (data.aiInsights?.weaknesses && data.aiInsights.weaknesses.length > 0) {
    data.aiInsights.weaknesses.forEach(w => rows.push([w]))
  }
  rows.push([''])

  if (data.aiInsights?.topOpportunity) {
    rows.push(['TOP OPPORTUNITY'])
    rows.push([data.aiInsights.topOpportunity])
    rows.push([''])
  }

  rows.push(['TOP KEYWORDS'])
  rows.push(['Keyword', 'Position', 'Volume', 'Traffic'])
  data.topKeywords.forEach(k => {
    rows.push([k.keyword, String(k.position), String(k.volume), String(k.traffic)])
  })
  rows.push([''])

  rows.push(['TOP PAGES'])
  rows.push(['Title', 'URL', 'Traffic'])
  data.topPages.forEach(p => {
    rows.push([p.title, p.url, String(p.traffic)])
  })
  rows.push([''])

  rows.push(['TOP BACKLINK SOURCES'])
  rows.push(['Domain', 'Links', 'Domain Authority'])
  data.topBacklinks.forEach(b => {
    rows.push([b.domain, String(b.links), String(b.da)])
  })
  rows.push([''])

  rows.push(['KEYWORD GAPS (Opportunities)'])
  rows.push(['Keyword', 'Volume', 'Difficulty'])
  data.gapKeywords.forEach(g => {
    rows.push([g.keyword, String(g.volume), String(g.difficulty)])
  })
  rows.push([''])

  rows.push(['CONTENT OPPORTUNITIES'])
  rows.push(['Title', 'Opportunity', 'Potential Traffic'])
  data.contentOpps.forEach(c => {
    rows.push([c.title, c.opportunity, String(c.traffic)])
  })

  downloadCSV('Optmizly-competitor-spy.csv', rows)
}

export function exportCompetitorSpyPDF(data: CompetitorSpyData) {
  const strengthsList = (data.aiInsights?.strengths ?? []).map(s => `<li style="margin:4px 0;font-size:11px">${s}</li>`).join('')
  const weaknessList = (data.aiInsights?.weaknesses ?? []).map(w => `<li style="margin:4px 0;font-size:11px">${w}</li>`).join('')
  const keywordRows = data.topKeywords.map(k => `
    <tr><td>${k.keyword}</td><td style="text-align:right">${k.position}</td><td style="text-align:right">${k.volume.toLocaleString()}</td><td style="text-align:right">${k.traffic.toLocaleString()}</td></tr>`).join('')
  const pageRows = data.topPages.map(p => `
    <tr><td style="word-break:break-all;font-size:10px">${p.url}</td><td style="text-align:right">${p.traffic.toLocaleString()}</td></tr>`).join('')
  const backlinkRows = data.topBacklinks.map(b => `
    <tr><td>${b.domain}</td><td style="text-align:right">${b.links}</td><td style="text-align:right">${b.da}</td></tr>`).join('')
  const gapRows = data.gapKeywords.map(g => `
    <tr><td>${g.keyword}</td><td style="text-align:right">${g.volume.toLocaleString()}</td><td style="text-align:right;background:#fee2e2;color:#dc2626;font-weight:600">${g.difficulty}</td></tr>`).join('')
  const oppRows = data.contentOpps.map(c => `
    <tr><td>${c.title}</td><td style="font-size:10px">${c.opportunity}</td><td style="text-align:right">${c.traffic.toLocaleString()}</td></tr>`).join('')

  const threatColor = !data.aiInsights?.threatLevel ? 'bg-green-100 text-green-700' : data.aiInsights.threatLevel === 'high' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700'
  const threatLevel = data.aiInsights?.threatLevel?.toUpperCase() || 'LOW'

  const html = `
    <h1>Competitor Analysis Report</h1>
    <p class="meta">${data.domainName} · ${data.domainUrl} · Generated by Optmizly · ${new Date(data.lastAnalyzedAt).toLocaleDateString()}</p>

    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 16px 4px 0"><strong>Threat Level</strong></td><td><span class="badge ${threatColor}">${threatLevel}</span></td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Est. Monthly Traffic</strong></td><td>${data.estimatedTraffic.toLocaleString()}</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Domain Authority</strong></td><td>${data.domainAuthority}</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Backlinks</strong></td><td>${data.backlinksTotal.toLocaleString()}</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Keywords Ranked</strong></td><td>${data.keywordCount.toLocaleString()}</td></tr>
    </table>

    ${data.aiInsights ? `<h2>Competitive Analysis</h2>
    <div style="background:#f8fafc;padding:12px;border-radius:6px;margin-bottom:16px">
      ${data.aiInsights.strengths && data.aiInsights.strengths.length > 0 ? `
        <h3 style="color:#16a34a;margin:0 0 6px 0;font-size:12px;font-weight:600">Strengths</h3>
        <ul style="margin:4px 0 12px 20px;padding:0">${strengthsList}</ul>
      ` : ''}
      ${data.aiInsights.weaknesses && data.aiInsights.weaknesses.length > 0 ? `
        <h3 style="color:#dc2626;margin:0 0 6px 0;font-size:12px;font-weight:600">Weaknesses</h3>
        <ul style="margin:4px 0 12px 20px;padding:0">${weaknessList}</ul>
      ` : ''}
      ${data.aiInsights.topOpportunity ? `
        <h3 style="color:#1e3a8a;margin:0 0 6px 0;font-size:12px;font-weight:600">Top Opportunity</h3>
        <p style="margin:4px 0;font-size:11px">${data.aiInsights.topOpportunity}</p>
      ` : ''}
    </div>` : ''}

    <h2>Top Keywords (${data.topKeywords.length})</h2>
    <table><thead><tr><th>Keyword</th><th style="width:50px">Position</th><th style="width:60px">Volume</th><th style="width:60px">Traffic</th></tr></thead><tbody>${keywordRows}</tbody></table>

    <h2>Top Pages (${data.topPages.length})</h2>
    <table><thead><tr><th style="width:400px">URL</th><th style="text-align:right;width:80px">Traffic</th></tr></thead><tbody>${pageRows}</tbody></table>

    <h2>Top Backlink Sources (${data.topBacklinks.length})</h2>
    <table><thead><tr><th>Domain</th><th style="width:50px;text-align:right">Links</th><th style="width:80px;text-align:right">DA</th></tr></thead><tbody>${backlinkRows}</tbody></table>

    <h2>Keyword Gaps - Opportunities (${data.gapKeywords.length})</h2>
    <table><thead><tr><th>Keyword</th><th style="width:60px;text-align:right">Volume</th><th style="width:60px;text-align:right">Difficulty</th></tr></thead><tbody>${gapRows}</tbody></table>

    <h2>Content Opportunities (${data.contentOpps.length})</h2>
    <table><thead><tr><th>Title</th><th style="width:250px">Opportunity</th><th style="width:80px;text-align:right">Traffic</th></tr></thead><tbody>${oppRows}</tbody></table>`

  downloadPDF('Optmizly Competitor Spy Report', html)
}

// ─────────────────────────────────────────────────────────────────────────────
// RANK TRACKER EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type HistoryPoint = { rank: number | null; checkedDate: string }

type RTKeyword = {
  id: string
  keyword: string
  searchVolume: number | null
  difficulty: number | null
  currentRank: number | null
  currentUrl: string | null
  rankChange7d: number | null
  rankChange30d: number | null
  rankTrendPercent: number | null
  status: string
  lastRanked: string | null
  history: HistoryPoint[]
}

type RTAlert = {
  id: string
  keyword: string
  alertType: string
  oldRank: number | null
  newRank: number | null
  message: string
  read: boolean
  createdAt: string
}

type RankTrackerData = {
  id: string
  name: string
  domain: string
  targetLocation: string
  deviceType: string
  lastUpdatedAt: string | null
  keywords: RTKeyword[]
  alerts: RTAlert[]
}

export function exportRankTrackerCSV(data: RankTrackerData) {
  const rows: string[][] = []

  rows.push(['RANK TRACKER REPORT'])
  rows.push(['Project', data.name])
  rows.push(['Domain', data.domain])
  rows.push(['Location', data.targetLocation])
  rows.push(['Device', data.deviceType])
  rows.push(['Last Updated', data.lastUpdatedAt ? new Date(data.lastUpdatedAt).toLocaleDateString() : 'Never'])
  rows.push(['Export Date', new Date().toLocaleDateString()])
  rows.push([''])

  // Summary stats
  const ranking = data.keywords.filter(k => k.currentRank !== null && k.currentRank <= 100).length
  const top3 = data.keywords.filter(k => k.currentRank !== null && k.currentRank <= 3).length
  const top10 = data.keywords.filter(k => k.currentRank !== null && k.currentRank <= 10).length
  const avgRank = data.keywords.length ? Math.round(data.keywords.reduce((sum, k) => sum + (k.currentRank ?? 101), 0) / data.keywords.length) : null

  rows.push(['SUMMARY'])
  rows.push(['Total Keywords', String(data.keywords.length)])
  rows.push(['Ranking Keywords', String(ranking)])
  rows.push(['Top 3', String(top3)])
  rows.push(['Top 10', String(top10)])
  rows.push(['Average Rank', avgRank ? `#${avgRank}` : '—'])
  rows.push([''])

  rows.push(['KEYWORD RANKINGS'])
  rows.push(['Keyword', 'Current Rank', 'URL', 'Search Volume', 'Difficulty', 'Change 7d', 'Change 30d', 'Status', 'Last Ranked'])
  data.keywords.forEach(k => {
    rows.push([
      k.keyword,
      k.currentRank ? `#${k.currentRank}` : '—',
      k.currentUrl ?? '—',
      k.searchVolume ? String(k.searchVolume.toLocaleString()) : '—',
      k.difficulty ? String(k.difficulty) : '—',
      k.rankChange7d ? (k.rankChange7d > 0 ? `↑${k.rankChange7d}` : `↓${Math.abs(k.rankChange7d)}`) : '—',
      k.rankChange30d ? (k.rankChange30d > 0 ? `↑${k.rankChange30d}` : `↓${Math.abs(k.rankChange30d)}`) : '—',
      k.status,
      k.lastRanked ? new Date(k.lastRanked).toLocaleDateString() : '—'
    ])
  })
  rows.push([''])

  if (data.alerts.length > 0) {
    rows.push(['RECENT ALERTS'])
    rows.push(['Keyword', 'Alert Type', 'Old Rank', 'New Rank', 'Message', 'Date'])
    data.alerts.slice(0, 50).forEach(a => {
      rows.push([
        a.keyword,
        a.alertType,
        a.oldRank ? `#${a.oldRank}` : '—',
        a.newRank ? `#${a.newRank}` : '—',
        a.message,
        new Date(a.createdAt).toLocaleDateString()
      ])
    })
  }

  downloadCSV('Optmizly-rank-tracker.csv', rows)
}

export function exportRankTrackerPDF(data: RankTrackerData) {
  const ranking = data.keywords.filter(k => k.currentRank !== null && k.currentRank <= 100).length
  const top3 = data.keywords.filter(k => k.currentRank !== null && k.currentRank <= 3).length
  const top10 = data.keywords.filter(k => k.currentRank !== null && k.currentRank <= 10).length
  const avgRank = data.keywords.length ? Math.round(data.keywords.reduce((sum, k) => sum + (k.currentRank ?? 101), 0) / data.keywords.length) : null

  const keywordRows = data.keywords.map(k => `
    <tr>
      <td style="font-weight:600">${k.keyword}</td>
      <td style="text-align:center">${k.currentRank ? `<strong>#${k.currentRank}</strong>` : '—'}</td>
      <td style="font-size:10px;color:#6b7280">${k.currentUrl ?? '—'}</td>
      <td style="text-align:right;font-size:10px">${k.searchVolume ? k.searchVolume.toLocaleString() : '—'}</td>
      <td style="text-align:center"><span class="badge ${k.difficulty === null ? '' : k.difficulty <= 30 ? 'low' : k.difficulty <= 60 ? 'medium' : 'high'}">${k.difficulty ?? '—'}</span></td>
      <td style="text-align:center;font-size:11px;font-weight:600">${k.rankChange7d ? (k.rankChange7d > 0 ? '<span style="color:#16a34a">↑' + k.rankChange7d + '</span>' : '<span style="color:#dc2626">↓' + Math.abs(k.rankChange7d) + '</span>') : '—'}</td>
      <td style="text-align:center;font-size:11px;font-weight:600">${k.rankChange30d ? (k.rankChange30d > 0 ? '<span style="color:#16a34a">↑' + k.rankChange30d + '</span>' : '<span style="color:#dc2626">↓' + Math.abs(k.rankChange30d) + '</span>') : '—'}</td>
    </tr>`).join('')

  const alertRows = data.alerts.slice(0, 30).map(a => {
    const iconMap: Record<string, string> = {
      'top_3': '🥇', 'first_page': '📄', 'position_gain': '🚀', 'position_drop': '📉',
      'new_ranking': '🆕', 'lost_ranking': '⚠ï¸',
    }
    return `<tr>
      <td>${iconMap[a.alertType] ?? '🔔'} ${a.keyword}</td>
      <td style="font-size:10px">${a.message}</td>
      <td style="text-align:right;font-size:10px">${new Date(a.createdAt).toLocaleDateString()}</td>
    </tr>`
  }).join('')

  const html = `
    <h1>Rank Tracker Report</h1>
    <p class="meta">${data.name} · ${data.domain} · ${data.targetLocation} · ${data.deviceType} · Generated by Optmizly · ${new Date().toLocaleDateString()}</p>

    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 16px 4px 0"><strong>Total Keywords</strong></td><td style="font-size:18px;font-weight:900;color:#1e3a8a">${data.keywords.length}</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Ranking</strong></td><td>${ranking}</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Top 3</strong></td><td style="font-size:16px;font-weight:900;color:#16a34a">${top3}</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Top 10</strong></td><td style="font-size:16px;font-weight:900;color:#3b82f6">${top10}</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Average Rank</strong></td><td>${avgRank ? '#' + avgRank : '—'}</td></tr>
    </table>

    <h2>Keyword Rankings (${data.keywords.length})</h2>
    <table><thead><tr><th>Keyword</th><th style="width:50px">Rank</th><th style="width:200px">URL</th><th style="width:60px">Volume</th><th style="width:50px">KD</th><th style="width:60px">7d</th><th style="width:60px">30d</th></tr></thead><tbody>${keywordRows}</tbody></table>

    ${data.alerts.length > 0 ? `<h2>Recent Alerts (${Math.min(data.alerts.length, 30)} of ${data.alerts.length})</h2>
    <table><thead><tr><th>Keyword & Alert</th><th style="width:250px">Message</th><th style="width:80px;text-align:right">Date</th></tr></thead><tbody>${alertRows}</tbody></table>` : ''}`

  downloadPDF('Optmizly Rank Tracker Report', html)
}

// ─────────────────────────────────────────────────────────────────────────────
// CONTENT IDEAS EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type ContentIdea = {
  id: string
  title: string
  slug: string
  description: string | null
  primaryKeyword: string
  relatedKeywords: string
  searchVolume: number
  difficulty: number
  cpc: number | null
  contentType: string
  estimatedLength: number
  sections: string
  entitiesNeeded: string
  lsiKeywords: string
  semanticGaps: string
  eeatScore: number
  competitorCount: number
  opportunityScore: number
  status: string
  pinned: boolean
  notes: string | null
  aiOutline: string | null
  aiIntro: string | null
  createdAt: string
  project: { name: string; industry: string }
}

type ContentIdeasData = {
  ideas: ContentIdea[]
  projectName?: string
  projectIndustry?: string
}

export function exportContentIdeasCSV(data: ContentIdeasData) {
  const rows: string[][] = []

  rows.push(['CONTENT IDEAS REPORT'])
  if (data.projectName) {
    rows.push(['Project', data.projectName])
    if (data.projectIndustry) rows.push(['Industry', data.projectIndustry])
  }
  rows.push(['Export Date', new Date().toLocaleDateString()])
  rows.push(['Total Ideas', String(data.ideas.length)])
  rows.push([''])

  rows.push(['CONTENT IDEAS'])
  rows.push(['Title', 'Primary Keyword', 'Type', 'Status', 'Search Volume', 'Difficulty', 'Opportunity', 'Est. Length', 'E-E-A-T', 'Competitors', 'Related Keywords', 'Notes'])

  data.ideas.forEach(idea => {
    rows.push([
      idea.title,
      idea.primaryKeyword,
      idea.contentType,
      idea.status,
      String(idea.searchVolume),
      String(idea.difficulty),
      String(idea.opportunityScore),
      String(idea.estimatedLength) + ' words',
      String(idea.eeatScore),
      String(idea.competitorCount),
      idea.relatedKeywords,
      idea.notes ?? ''
    ])
  })
  rows.push([''])

  // Summary by type
  const byType = data.ideas.reduce((acc, idea) => {
    const t = idea.contentType
    if (!acc[t]) acc[t] = 0
    acc[t]++
    return acc
  }, {} as Record<string, number>)

  if (Object.keys(byType).length > 0) {
    rows.push(['BREAKDOWN BY CONTENT TYPE'])
    rows.push(['Type', 'Count'])
    Object.entries(byType).forEach(([type, count]) => {
      rows.push([type, String(count)])
    })
    rows.push([''])
  }

  // Summary by status
  const byStatus = data.ideas.reduce((acc, idea) => {
    const s = idea.status
    if (!acc[s]) acc[s] = 0
    acc[s]++
    return acc
  }, {} as Record<string, number>)

  if (Object.keys(byStatus).length > 0) {
    rows.push(['BREAKDOWN BY STATUS'])
    rows.push(['Status', 'Count'])
    Object.entries(byStatus).forEach(([status, count]) => {
      rows.push([status, String(count)])
    })
  }

  downloadCSV('Optmizly-content-ideas.csv', rows)
}

export function exportContentIdeasPDF(data: ContentIdeasData) {
  const ideasByType = data.ideas.reduce((acc, idea) => {
    const t = idea.contentType
    if (!acc[t]) acc[t] = 0
    acc[t]++
    return acc
  }, {} as Record<string, number>)

  const ideasByStatus = data.ideas.reduce((acc, idea) => {
    const s = idea.status
    if (!acc[s]) acc[s] = 0
    acc[s]++
    return acc
  }, {} as Record<string, number>)

  const topByOpportunity = [...data.ideas].sort((a, b) => b.opportunityScore - a.opportunityScore).slice(0, 10)
  const highVolume = data.ideas.filter(i => i.searchVolume >= 1000).length

  const ideaRows = data.ideas.map(idea => `
    <tr>
      <td style="font-weight:600">${idea.title}</td>
      <td>${idea.primaryKeyword}</td>
      <td style="font-size:10px">${idea.contentType}</td>
      <td style="font-size:10px"><span class="badge ${idea.status === 'published' ? 'low' : idea.status === 'writing' ? 'medium' : idea.status === 'idea' ? 'high' : 'medium'}">${idea.status}</span></td>
      <td style="text-align:right;font-size:10px">${idea.searchVolume.toLocaleString()}</td>
      <td style="text-align:center;font-size:10px;font-weight:600;color:${idea.difficulty <= 30 ? '#16a34a' : idea.difficulty <= 60 ? '#d97706' : '#dc2626'}">${idea.difficulty}</td>
      <td style="text-align:center;font-weight:600;color:${idea.opportunityScore >= 70 ? '#16a34a' : idea.opportunityScore >= 50 ? '#d97706' : '#6b7280'}">${idea.opportunityScore}</td>
    </tr>`).join('')

  const typeRows = Object.entries(ideasByType).map(([type, count]) =>
    `<tr><td>${type}</td><td style="text-align:right">${count}</td></tr>`).join('')

  const statusRows = Object.entries(ideasByStatus).map(([status, count]) =>
    `<tr><td style="text-transform:capitalize">${status}</td><td style="text-align:right">${count}</td></tr>`).join('')

  const html = `
    <h1>Content Ideas Report</h1>
    <p class="meta">${data.projectName ? `${data.projectName} · ${data.projectIndustry ?? ''}` : 'All Projects'} · Generated by Optmizly · ${new Date().toLocaleDateString()}</p>

    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 16px 4px 0"><strong>Total Ideas</strong></td><td style="font-size:18px;font-weight:900;color:#1e3a8a">${data.ideas.length}</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>High Volume (1k+)</strong></td><td style="font-size:16px;font-weight:900;color:#3b82f6">${highVolume}</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Avg Opportunity Score</strong></td><td>${Math.round(data.ideas.reduce((sum, i) => sum + i.opportunityScore, 0) / data.ideas.length)}</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Avg Est. Length</strong></td><td>${Math.round(data.ideas.reduce((sum, i) => sum + i.estimatedLength, 0) / data.ideas.length)} words</td></tr>
    </table>

    <h2>Top Opportunities (by Score)</h2>
    <table><thead><tr><th>Title</th><th>Keyword</th><th>Type</th><th style="width:60px">Volume</th><th style="width:50px">Score</th></tr></thead><tbody>${topByOpportunity.map(idea => `
      <tr>
        <td style="font-weight:600">${idea.title}</td>
        <td>${idea.primaryKeyword}</td>
        <td style="font-size:10px">${idea.contentType}</td>
        <td style="text-align:right;font-size:10px">${idea.searchVolume.toLocaleString()}</td>
        <td style="text-align:center;font-weight:600;color:${idea.opportunityScore >= 70 ? '#16a34a' : '#d97706'}">${idea.opportunityScore}</td>
      </tr>`).join('')}</tbody></table>

    <h2>All Ideas (${data.ideas.length})</h2>
    <table><thead><tr><th>Title</th><th>Keyword</th><th>Type</th><th style="width:60px">Status</th><th style="width:70px">Volume</th><th style="width:50px">KD</th><th style="width:60px">Opp.</th></tr></thead><tbody>${ideaRows}</tbody></table>

    <h2>Content Type Breakdown</h2>
    <table><thead><tr><th>Type</th><th style="width:50px;text-align:right">Count</th></tr></thead><tbody>${typeRows}</tbody></table>

    <h2>Status Breakdown</h2>
    <table><thead><tr><th>Status</th><th style="width:50px;text-align:right">Count</th></tr></thead><tbody>${statusRows}</tbody></table>`

  downloadPDF('Optmizly Content Ideas Report', html)
}

// ─────────────────────────────────────────────────────────────────────────────
// BACKLINKS PROJECT EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type BacklinksOpportunity = {
  id: string
  siteName: string
  siteUrl: string
  domainAuthority: string
  linkType: string
  angle: string
  whyRelevant: string
  contactApproach: string
  difficulty: string
  impact: string
  status: string
  notes: string | null
}

type BacklinksProject = {
  id: string
  name: string
  domain: string
  niche: string
  targetKeywords: string[]
  contentBrief: string
  aiSummary: string | null
  opportunities: BacklinksOpportunity[]
  createdAt: string
}

export function exportBacklinksProjectCSV(data: BacklinksProject) {
  const rows: string[][] = []

  rows.push(['BACKLINKS OUTREACH PROJECT'])
  rows.push(['Project', data.name])
  rows.push(['Domain', data.domain])
  rows.push(['Niche', data.niche])
  rows.push(['Target Keywords', data.targetKeywords.join(', ')])
  rows.push(['Export Date', new Date().toLocaleDateString()])
  rows.push([''])

  // Summary stats
  const statusCount = data.opportunities.reduce((acc, opp) => {
    acc[opp.status] = (acc[opp.status] ?? 0) + 1
    return acc
  }, {} as Record<string, number>)

  rows.push(['SUMMARY'])
  rows.push(['Total Opportunities', String(data.opportunities.length)])
  rows.push(['Prospecting', String(statusCount.prospecting ?? 0)])
  rows.push(['Contacted', String(statusCount.contacted ?? 0)])
  rows.push(['Replied', String(statusCount.replied ?? 0)])
  rows.push(['Secured', String(statusCount.secured ?? 0)])
  rows.push(['Rejected', String(statusCount.rejected ?? 0)])
  rows.push([''])

  rows.push(['OPPORTUNITIES'])
  rows.push(['Site Name', 'URL', 'Domain Authority', 'Link Type', 'Pitch Angle', 'Why Relevant', 'Contact Approach', 'Difficulty', 'Impact', 'Status', 'Notes'])
  data.opportunities.forEach(opp => {
    rows.push([
      opp.siteName,
      opp.siteUrl,
      opp.domainAuthority,
      opp.linkType,
      opp.angle,
      opp.whyRelevant,
      opp.contactApproach,
      opp.difficulty,
      opp.impact,
      opp.status,
      opp.notes ?? ''
    ])
  })

  downloadCSV('optmizly-backlinks-project.csv', rows)
}

export function exportBacklinksProjectPDF(data: BacklinksProject) {
  const statusCount = data.opportunities.reduce((acc, opp) => {
    acc[opp.status] = (acc[opp.status] ?? 0) + 1
    return acc
  }, {} as Record<string, number>)

  const total = data.opportunities.length
  const secured = statusCount.secured ?? 0
  const replied = statusCount.replied ?? 0
  const contacted = statusCount.contacted ?? 0

  const oppRows = data.opportunities.map(opp => {
    const statusColors: Record<string, string> = {
      prospecting: 'bg-slate-100 text-slate-600',
      contacted: 'bg-blue-100 text-blue-700',
      replied: 'bg-amber-100 text-amber-700',
      secured: 'bg-green-100 text-green-700',
      rejected: 'bg-red-100 text-red-600',
    }
    const daColors: Record<string, string> = {
      high: 'bg-purple-50 text-purple-700',
      medium: 'bg-blue-50 text-blue-700',
      low: 'bg-slate-50 text-slate-600',
    }
    const impactColors: Record<string, string> = {
      high: 'bg-green-100 text-green-700',
      medium: 'bg-blue-100 text-blue-700',
      low: 'bg-slate-100 text-slate-600',
    }
    return `<tr>
      <td style="font-weight:600">${opp.siteName}</td>
      <td style="font-size:10px;color:#6b7280">${opp.siteUrl}</td>
      <td><span class="badge ${daColors[opp.domainAuthority] ?? daColors.low}">${opp.domainAuthority}</span></td>
      <td style="font-size:10px">${opp.linkType.replace(/_/g, ' ')}</td>
      <td style="font-size:10px;color:#6b7280">${opp.angle}</td>
      <td style="font-size:10px;color:#6b7280">${opp.whyRelevant}</td>
      <td style="font-size:10px;color:#6b7280">${opp.contactApproach}</td>
      <td><span class="badge ${opp.difficulty === 'hard' ? 'high' : opp.difficulty === 'medium' ? 'medium' : 'low'}">${opp.difficulty}</span></td>
      <td><span class="badge ${impactColors[opp.impact] ?? impactColors.medium}">${opp.impact}</span></td>
      <td><span class="badge ${statusColors[opp.status] ?? statusColors.prospecting}">${opp.status}</span></td>
    </tr>`
  }).join('')

  const html = `
    <h1>Backlinks Outreach Project</h1>
    <p class="meta">${data.name} · ${data.domain} · ${data.niche} · Generated by Optmizly · ${new Date(data.createdAt).toLocaleDateString()}</p>

    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 16px 4px 0"><strong>Total Opportunities</strong></td><td style="font-size:18px;font-weight:900;color:#1e3a8a">${total}</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Secured</strong></td><td style="font-size:16px;font-weight:900;color:#16a34a">${secured}</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>Conversion Rate</strong></td><td>${total > 0 ? Math.round((secured / total) * 100) : 0}%</td></tr>
      <tr><td style="padding:4px 16px 4px 0"><strong>In Progress</strong></td><td>${contacted + replied}</td></tr>
    </table>

    ${data.aiSummary ? `<h2>Project Summary</h2>
    <p style="line-height:1.6;margin-bottom:16px">${data.aiSummary}</p>` : ''}

    <h2>Outreach Status</h2>
    <div style="display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:16px">
      <div style="background:#f8fafc;padding:12px;border-radius:6px;text-align:center">
        <div style="font-size:20px;font-weight:900;color:#10b981">${secured}</div>
        <div style="font-size:11px;color:#6b7280">Secured</div>
      </div>
      <div style="background:#f8fafc;padding:12px;border-radius:6px;text-align:center">
        <div style="font-size:20px;font-weight:900;color:#f59e0b">${replied}</div>
        <div style="font-size:11px;color:#6b7280">Replied</div>
      </div>
      <div style="background:#f8fafc;padding:12px;border-radius:6px;text-align:center">
        <div style="font-size:20px;font-weight:900;color:#3b82f6">${contacted}</div>
        <div style="font-size:11px;color:#6b7280">Contacted</div>
      </div>
      <div style="background:#f8fafc;padding:12px;border-radius:6px;text-align:center">
        <div style="font-size:20px;font-weight:900;color:#6b7280">${statusCount.prospecting ?? 0}</div>
        <div style="font-size:11px;color:#6b7280">Prospecting</div>
      </div>
      <div style="background:#f8fafc;padding:12px;border-radius:6px;text-align:center">
        <div style="font-size:20px;font-weight:900;color:#dc2626">${statusCount.rejected ?? 0}</div>
        <div style="font-size:11px;color:#6b7280">Rejected</div>
      </div>
    </div>

    <h2>Opportunities (${data.opportunities.length})</h2>
    <table><thead><tr><th>Site Name</th><th style="width:150px">URL</th><th style="width:60px">DA</th><th>Type</th><th>Angle</th><th>Relevance</th><th>Contact</th><th>Diff</th><th>Impact</th><th>Status</th></tr></thead><tbody>${oppRows}</tbody></table>`

  downloadPDF('Optmizly Backlinks Project Report', html)
}

// ─────────────────────────────────────────────────────────────────────────────
// CONTENT OPTIMIZER EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type Entity = { name: string; type: string; strength: 'strong' | 'weak'; frequency: number }
type MissingEntity = { name: string; reason: string; where: string }
type EntityRelationship = { entity1: string; entity2: string; relationship: string }
type Suggestion = { issue: string; suggestion: string; priority: 'critical' | 'warning' | 'info' }
type Rewrite = { section: string; original: string; improved: string }
type Fix = { issue: string; suggestion: string; beforeText?: string; afterText?: string; priority: 'critical' | 'warning' | 'info' }
type MissingTopic = { topic: string; importance: string; reason: string }
type ClusterPage = { title: string; topic: string; importance: string }
type LinkingOp = { from: string; to: string; anchor: string }

type ContentOptimizerResult = {
  id: string
  overallScore: number
  intent: { intent: string; matchScore: number; reasoning: string; suggestions: Suggestion[] }
  entities: { entities: Entity[]; score: number; missing: MissingEntity[]; relationships: EntityRelationship[]; suggestions: Suggestion[] }
  lsi: { found: string[]; missing: string[]; score: number; suggestions: Suggestion[] }
  schema: { type: string; reasoning: string; jsonLd: string }
  topics: { mainTopic: string; covered: string[]; missing: MissingTopic[]; score: number; pillarSuggestion: string; clusterSuggestions: ClusterPage[]; linkingOpportunities: LinkingOp[]; suggestions: Suggestion[] }
  eeat: { experience: number; expertise: number; authority: number; trust: number; overall: number; details: Record<string, string> }
  improvements: { contentScore: number; fixes: Fix[]; rewrites: Rewrite[] }
}

export function exportContentOptimizerCSV(data: ContentOptimizerResult) {
  const rows: string[][] = []

  rows.push(['CONTENT OPTIMIZER ANALYSIS REPORT'])
  rows.push(['Date', new Date().toLocaleDateString()])
  rows.push([''])

  rows.push(['OVERALL SCORE', String(data.overallScore), '/100'])
  rows.push([''])

  // Intent Analysis
  rows.push(['SEARCH INTENT'])
  rows.push(['Intent Type', data.intent.intent])
  rows.push(['Match Score', String(data.intent.matchScore), '/100'])
  rows.push(['Reasoning', data.intent.reasoning])
  if (data.intent.suggestions.length > 0) {
    rows.push(['Suggestions'])
    data.intent.suggestions.forEach(s => rows.push([s.issue, s.suggestion]))
  }
  rows.push([''])

  // Entities
  rows.push(['ENTITIES ANALYSIS'])
  rows.push(['Score', String(data.entities.score), '/100'])
  if (data.entities.entities.length > 0) {
    rows.push(['Found Entities'])
    rows.push(['Entity', 'Type', 'Strength', 'Frequency'])
    data.entities.entities.forEach(e => rows.push([e.name, e.type, e.strength, String(e.frequency)]))
  }
  if (data.entities.missing.length > 0) {
    rows.push(['Missing Entities'])
    rows.push(['Entity', 'Reason', 'Where to Add'])
    data.entities.missing.forEach(m => rows.push([m.name, m.reason, m.where]))
  }
  rows.push([''])

  // LSI Keywords
  rows.push(['LSI KEYWORDS'])
  rows.push(['Score', String(data.lsi.score), '/100'])
  rows.push(['Found Keywords', data.lsi.found.join(', ')])
  rows.push(['Missing Keywords', data.lsi.missing.join(', ')])
  rows.push([''])

  // Topics
  rows.push(['TOPIC COVERAGE'])
  rows.push(['Score', String(data.topics.score), '/100'])
  rows.push(['Main Topic', data.topics.mainTopic])
  rows.push(['Covered Topics', data.topics.covered.join(', ')])
  if (data.topics.missing.length > 0) {
    rows.push(['Missing Topics'])
    rows.push(['Topic', 'Importance', 'Reason'])
    data.topics.missing.forEach(m => rows.push([m.topic, m.importance, m.reason]))
  }
  rows.push([''])

  // E-E-A-T
  rows.push(['E-E-A-T DIMENSIONS'])
  rows.push(['Experience', String(data.eeat.experience)])
  rows.push(['Expertise', String(data.eeat.expertise)])
  rows.push(['Authority', String(data.eeat.authority)])
  rows.push(['Trust', String(data.eeat.trust)])
  rows.push(['Overall', String(data.eeat.overall)])
  rows.push([''])

  // Improvements
  rows.push(['RECOMMENDED IMPROVEMENTS'])
  rows.push(['Content Score', String(data.improvements.contentScore)])
  if (data.improvements.fixes.length > 0) {
    rows.push(['Fixes'])
    rows.push(['Issue', 'Suggestion', 'Priority'])
    data.improvements.fixes.forEach(f => rows.push([f.issue, f.suggestion, f.priority]))
  }

  downloadCSV('Optmizly-content-optimizer.csv', rows)
}

export function exportContentOptimizerPDF(data: ContentOptimizerResult) {
  const scoreColor = (score: number) => score >= 80 ? '#16a34a' : score >= 60 ? '#f59e0b' : '#dc2626'

  const entitiesRows = data.entities.entities.map(e => `
    <tr><td>${e.name}</td><td style="font-size:10px">${e.type}</td><td style="font-size:10px">${e.strength}</td><td style="text-align:right">${e.frequency}</td></tr>`).join('')

  const suggestionsRows = data.intent.suggestions.map(s => `
    <tr><td>${s.issue}</td><td style="font-size:10px">${s.suggestion}</td><td><span class="badge ${s.priority === 'critical' ? 'high' : s.priority === 'warning' ? 'medium' : 'low'}">${s.priority}</span></td></tr>`).join('')

  const fixesRows = data.improvements.fixes.map(f => `
    <tr><td>${f.issue}</td><td style="font-size:10px">${f.suggestion}</td><td><span class="badge ${f.priority === 'critical' ? 'high' : f.priority === 'warning' ? 'medium' : 'low'}">${f.priority}</span></td></tr>`).join('')

  const html = `
    <h1>Content Optimizer Analysis Report</h1>
    <p class="meta">Generated by Optmizly · ${new Date().toLocaleDateString()}</p>

    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 16px 4px 0"><strong>Overall Semantic SEO Score</strong></td><td style="font-size:28px;font-weight:900;color:${scoreColor(data.overallScore)}">${data.overallScore}</td><td style="padding-left:16px;color:#6b7280;font-size:12px">/100</td></tr>
    </table>

    <h2>Search Intent Analysis</h2>
    <table style="width:auto">
      <tr><td style="padding:4px 12px 4px 0"><strong>Intent Type</strong></td><td>${data.intent.intent}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Match Score</strong></td><td style="font-weight:600;color:${scoreColor(data.intent.matchScore)}">${data.intent.matchScore}/100</td></tr>
      <tr><td style="padding:4px 12px 4px 0;vertical-align:top"><strong>Reasoning</strong></td><td style="font-size:11px;color:#6b7280">${data.intent.reasoning}</td></tr>
    </table>
    ${suggestionsRows ? `<h3>Intent Suggestions</h3>
    <table><thead><tr><th>Issue</th><th>Suggestion</th><th>Priority</th></tr></thead><tbody>${suggestionsRows}</tbody></table>` : ''}

    <h2>Entities Analysis</h2>
    <table style="width:auto;margin-bottom:12px">
      <tr><td style="padding:4px 12px 4px 0"><strong>Entities Score</strong></td><td style="font-weight:600;color:${scoreColor(data.entities.score)}">${data.entities.score}/100</td></tr>
    </table>
    ${data.entities.entities.length > 0 ? `<h3>Found Entities (${data.entities.entities.length})</h3>
    <table><thead><tr><th>Entity</th><th>Type</th><th>Strength</th><th style="text-align:right">Frequency</th></tr></thead><tbody>${entitiesRows}</tbody></table>` : ''}

    <h2>LSI Keywords & Topic Coverage</h2>
    <table style="width:auto">
      <tr><td style="padding:4px 12px 4px 0"><strong>LSI Score</strong></td><td style="font-weight:600;color:${scoreColor(data.lsi.score)}">${data.lsi.score}/100</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Topics Score</strong></td><td style="font-weight:600;color:${scoreColor(data.topics.score)}">${data.topics.score}/100</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Main Topic</strong></td><td>${data.topics.mainTopic}</td></tr>
    </table>

    <h2>E-E-A-T Dimensions</h2>
    <table style="width:auto">
      <tr><td style="padding:4px 12px 4px 0"><strong>Experience</strong></td><td style="text-align:right;font-weight:600">${data.eeat.experience}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Expertise</strong></td><td style="text-align:right;font-weight:600">${data.eeat.expertise}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Authority</strong></td><td style="text-align:right;font-weight:600">${data.eeat.authority}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Trust</strong></td><td style="text-align:right;font-weight:600">${data.eeat.trust}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Overall E-E-A-T Score</strong></td><td style="text-align:right;font-weight:600;color:${scoreColor(data.eeat.overall)}">${data.eeat.overall}</td></tr>
    </table>

    ${data.improvements.fixes.length > 0 ? `<h2>Recommended Improvements</h2>
    <table><thead><tr><th>Issue</th><th>Suggestion</th><th>Priority</th></tr></thead><tbody>${fixesRows}</tbody></table>` : ''}`

  downloadPDF('Optmizly Content Optimizer Report', html)
}




